import type { FieldSpec } from "@/components/record-dialog";

export const INVENTORY_SCHEMAS: Record<string, FieldSpec[]> = {
  items: [
    { name: "code", label: "Item Code", type: "text", required: true, placeholder: "ITM-1000" },
    { name: "description", label: "Description", type: "text", required: true, colSpan: 2 },
    { name: "category", label: "Category", type: "select", required: true, options: ["Raw Material", "Component", "Sub-Assembly", "Finished Good", "Consumable"] },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "hsn", label: "HSN Code", type: "text" },
    { name: "tracking", label: "Tracking Mode", type: "select", required: true, options: ["none", "batch", "serial", "lot"] },
    { name: "stdCost", label: "Standard Cost (INR)", type: "number", required: true },
    { name: "reorder", label: "Reorder Level", type: "number", required: true },
    { name: "maxLevel", label: "Max Level", type: "number", required: true },
    { name: "shelfLifeDays", label: "Shelf Life (days)", type: "number" },
    { name: "onHand", label: "On Hand Qty", type: "number", required: true },
    { name: "allocated", label: "Allocated Qty", type: "number", required: true },
  ],
  stores: [
    { name: "code", label: "Store Code", type: "text", required: true, placeholder: "STR-C01" },
    { name: "name", label: "Store Name", type: "text", required: true, colSpan: 2 },
    { name: "type", label: "Type", type: "select", required: true, options: ["Central", "Shop-floor", "Bonded", "Scrap", "Project"] },
    { name: "location", label: "Location", type: "text", required: true },
    { name: "manager", label: "Store Manager", type: "text", required: true },
    { name: "bins", label: "Bin Count", type: "number", required: true },
    { name: "capacityUsedPct", label: "Capacity Used %", type: "number", required: true },
  ],
  bins: [
    { name: "code", label: "Bin Code", type: "text", required: true, placeholder: "A-01-02-03" },
    { name: "storeCode", label: "Store Code", type: "text", required: true },
    { name: "zone", label: "Zone", type: "text", required: true },
    { name: "aisle", label: "Aisle", type: "text", required: true },
    { name: "rack", label: "Rack", type: "text", required: true },
    { name: "level", label: "Level", type: "text", required: true },
    { name: "itemCode", label: "Item Code", type: "text" },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
  ],
  stock: [
    { name: "itemCode", label: "Item Code", type: "text", required: true },
    { name: "description", label: "Description", type: "text", required: true, colSpan: 2 },
    { name: "storeCode", label: "Store Code", type: "text", required: true },
    { name: "storeName", label: "Store Name", type: "text", required: true },
    { name: "binCode", label: "Bin Code", type: "text" },
    { name: "projectCode", label: "Project Code", type: "text" },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "value", label: "Value (INR)", type: "number", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["available", "reserved", "quality-hold", "in-transit"] },
  ],
  batches: [
    { name: "batchNo", label: "Batch / Lot Number", type: "text", required: true },
    { name: "itemCode", label: "Item Code", type: "text", required: true },
    { name: "description", label: "Description", type: "text", required: true, colSpan: 2 },
    { name: "serialFrom", label: "Serial From", type: "text" },
    { name: "serialTo", label: "Serial To", type: "text" },
    { name: "vendorName", label: "Vendor", type: "text" },
    { name: "mfgDate", label: "Manufactured On", type: "date", required: true },
    { name: "expiryDate", label: "Expires On", type: "date" },
    { name: "storeCode", label: "Store Code", type: "text", required: true },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "status", label: "Status", type: "select", required: true, options: ["available", "expiring", "expired", "quarantined"] },
  ],
  transfers: [
    { name: "code", label: "Document Number", type: "text", required: true, placeholder: "STO-9000" },
    { name: "type", label: "Type", type: "select", required: true, options: ["transfer", "adjustment", "issue", "return"] },
    { name: "itemCode", label: "Item Code", type: "text", required: true },
    { name: "description", label: "Description", type: "text", required: true, colSpan: 2 },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "fromStore", label: "From Store", type: "text", required: true },
    { name: "toStore", label: "To Store", type: "text" },
    { name: "projectCode", label: "Project Code", type: "text" },
    { name: "requestedBy", label: "Requested By", type: "text", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "requested", "in-transit", "received", "cancelled"] },
    { name: "reason", label: "Reason", type: "textarea", required: true, colSpan: 2 },
  ],
  counts: [
    { name: "code", label: "Count Number", type: "text", required: true, placeholder: "CC-2400" },
    { name: "storeCode", label: "Store Code", type: "text", required: true },
    { name: "storeName", label: "Store Name", type: "text", required: true },
    { name: "scheduledFor", label: "Scheduled For", type: "date", required: true },
    { name: "auditor", label: "Auditor", type: "text", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["planned", "in-progress", "reconciled", "posted"] },
    { name: "itemsPlanned", label: "Items Planned", type: "number", required: true },
    { name: "itemsCounted", label: "Items Counted", type: "number", required: true },
    { name: "variancesFound", label: "Variances Found", type: "number" },
    { name: "variancePct", label: "Variance %", type: "number" },
    { name: "varianceValue", label: "Variance Value (INR)", type: "number" },
  ],
};
