import type { FieldSpec } from "@/components/record-dialog";

export const FINANCE_SCHEMAS: Record<string, FieldSpec[]> = {
  accounts: [
    { name: "code", label: "Account Code", type: "text", required: true, placeholder: "e.g. 5300" },
    { name: "name", label: "Account Name", type: "text", required: true, colSpan: 2 },
    { name: "type", label: "Type", type: "select", required: true, options: ["asset", "liability", "equity", "income", "expense"] },
    { name: "parentCode", label: "Parent Account", type: "combobox", optionsKey: "accounts" },
    { name: "balance", label: "Opening Balance (INR)", type: "number", required: true },
    { name: "isControl", label: "Control Account", type: "select", options: ["yes", "no"] },
  ],
  journals: [
    { name: "code", label: "Journal No.", type: "text", placeholder: "auto-generated" },
    { name: "date", label: "Date", type: "date", required: true },
    { name: "reference", label: "Reference", type: "text", required: true },
    { name: "narration", label: "Narration", type: "textarea", required: true, colSpan: 2 },
    { name: "source", label: "Source", type: "select", required: true, options: ["manual", "AR", "AP", "bank", "payroll", "system"] },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "posted", "void"] },
    { name: "createdBy", label: "Created By", type: "text", required: true },
  ],
  journalLines: [
    { name: "accountCode", label: "Account", type: "combobox", optionsKey: "accounts", required: true, colSpan: 2 },
    { name: "projectCode", label: "Project", type: "combobox", optionsKey: "projects" },
    { name: "memo", label: "Memo", type: "text" },
    { name: "debit", label: "Debit (INR)", type: "number" },
    { name: "credit", label: "Credit (INR)", type: "number" },
  ],
  arInvoices: [
    { name: "code", label: "Invoice No.", type: "text", placeholder: "auto-generated" },
    { name: "customerName", label: "Customer", type: "combobox", optionsKey: "customers", required: true, colSpan: 2 },
    { name: "projectCode", label: "Project", type: "combobox", optionsKey: "projects" },
    { name: "issuedAt", label: "Issued On", type: "date", required: true },
    { name: "dueAt", label: "Due On", type: "date", required: true },
    { name: "amount", label: "Taxable Amount (INR)", type: "number", required: true },
    { name: "gst", label: "GST (INR)", type: "number" },
    { name: "tds", label: "TDS (INR)", type: "number" },
    { name: "received", label: "Received (INR)", type: "number" },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "sent", "partial", "paid", "overdue", "void"] },
    { name: "eInvoiceIRN", label: "e-Invoice IRN", type: "text" },
    { name: "ewayBillNo", label: "e-Way Bill No.", type: "text" },
  ],
  receipts: [
    { name: "receiptAmount", label: "Receipt Amount (INR)", type: "number", required: true },
    { name: "receiptDate", label: "Receipt Date", type: "date", required: true },
    { name: "bankCode", label: "Bank Account", type: "combobox", optionsKey: "banks", required: true },
    { name: "receiptRef", label: "UTR / Reference", type: "text" },
  ],
  apBills: [
    { name: "code", label: "Bill No.", type: "text", placeholder: "auto-generated" },
    { name: "vendorName", label: "Vendor", type: "combobox", optionsKey: "vendors", required: true, colSpan: 2 },
    { name: "poCode", label: "PO No.", type: "combobox", optionsKey: "pos" },
    { name: "grnCode", label: "GRN No.", type: "combobox", optionsKey: "grns" },
    { name: "receivedAt", label: "Received On", type: "date", required: true },
    { name: "dueAt", label: "Due On", type: "date", required: true },
    { name: "amount", label: "Taxable Amount (INR)", type: "number", required: true },
    { name: "gst", label: "GST (INR)", type: "number" },
    { name: "tds", label: "TDS (INR)", type: "number" },
    { name: "paid", label: "Paid (INR)", type: "number" },
    { name: "matchStatus", label: "3-Way Match", type: "select", required: true, options: ["matched", "price-var", "qty-var", "unmatched"] },
    { name: "status", label: "Status", type: "select", required: true, options: ["pending", "3wm-ok", "approved", "partial", "paid", "hold", "overdue"] },
  ],
  payments: [
    { name: "payAmount", label: "Payment Amount (INR)", type: "number", required: true },
    { name: "payDate", label: "Payment Date", type: "date", required: true },
    { name: "bankCode", label: "Bank Account", type: "combobox", optionsKey: "banks", required: true },
    { name: "payRef", label: "UTR / Reference", type: "text" },
  ],
  projectCosts: [
    { name: "projectCode", label: "Project Code", type: "combobox", optionsKey: "projects", required: true },
    { name: "projectName", label: "Project Name", type: "text", required: true, colSpan: 2 },
    { name: "customer", label: "Customer", type: "combobox", optionsKey: "customers", required: true },
    { name: "contractValue", label: "Contract Value (INR)", type: "number", required: true },
    { name: "billed", label: "Billed (INR)", type: "number", required: true },
    { name: "collected", label: "Collected (INR)", type: "number", required: true },
    { name: "materialCost", label: "Material Cost (INR)", type: "number", required: true },
    { name: "labourCost", label: "Labour Cost (INR)", type: "number", required: true },
    { name: "overheadCost", label: "Overhead Cost (INR)", type: "number", required: true },
    { name: "subContractCost", label: "Sub-Contract Cost (INR)", type: "number", required: true },
    { name: "committed", label: "Committed (INR)", type: "number", required: true },
    { name: "wip", label: "WIP (INR)", type: "number", required: true },
    { name: "percentComplete", label: "% Complete", type: "number", required: true },
    { name: "forecastCost", label: "Forecast Cost (INR)", type: "number", required: true },
  ],
  taxLedgers: [
    { name: "period", label: "Period", type: "text", required: true, placeholder: "Sep 2026" },
    { name: "type", label: "Return Type", type: "select", required: true, options: ["GSTR-1", "GSTR-3B", "TDS-26Q", "TDS-24Q", "e-Invoice"] },
    { name: "outputTax", label: "Output Tax (INR)", type: "number" },
    { name: "inputTax", label: "Input Tax / ITC (INR)", type: "number" },
    { name: "netPayable", label: "Net Payable (INR)", type: "number", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["open", "prepared", "filed", "late"] },
    { name: "reference", label: "Reference / ARN", type: "text" },
  ],
  bankAccounts: [
    { name: "code", label: "Account Code", type: "text", required: true, placeholder: "HDFC-CA-05" },
    { name: "bankName", label: "Bank", type: "text", required: true },
    { name: "accountNo", label: "Account No.", type: "text", required: true },
    { name: "branch", label: "Branch", type: "text", required: true },
    { name: "currency", label: "Currency", type: "select", required: true, options: ["INR", "USD", "EUR"] },
    { name: "bookBalance", label: "Book Balance (INR)", type: "number", required: true },
    { name: "statementBalance", label: "Statement Balance (INR)", type: "number", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["active", "dormant"] },
  ],
  bankTxns: [
    { name: "bankCode", label: "Bank Account", type: "combobox", optionsKey: "banks", required: true },
    { name: "date", label: "Date", type: "date", required: true },
    { name: "narration", label: "Narration", type: "text", required: true, colSpan: 2 },
    { name: "amount", label: "Amount (INR)", type: "number", required: true },
    { name: "direction", label: "Direction", type: "select", required: true, options: ["credit", "debit"] },
    { name: "matchedRef", label: "Matched Reference", type: "combobox", optionsKey: "openDocs" },
    { name: "status", label: "Status", type: "select", required: true, options: ["matched", "unmatched", "suggested"] },
  ],
  costCentres: [
    { name: "code", label: "Cost Centre Code", type: "text", required: true, placeholder: "CC-ENG" },
    { name: "name", label: "Name", type: "text", required: true, colSpan: 2 },
    { name: "type", label: "Type", type: "select", required: true, options: ["department", "plant", "business-unit", "project-pool"] },
    { name: "owner", label: "Owner", type: "text", required: true },
    { name: "budget", label: "Annual Budget (INR)", type: "number", required: true },
    { name: "actual", label: "YTD Actual (INR)", type: "number" },
    { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
  ],
  budgets: [
    { name: "code", label: "Budget Code", type: "text", placeholder: "auto-generated" },
    { name: "fiscalYear", label: "Fiscal Year", type: "select", required: true, options: ["FY2026", "FY2027"] },
    { name: "costCentreCode", label: "Cost Centre", type: "combobox", optionsKey: "costCentres", required: true },
    { name: "accountCode", label: "GL Account", type: "combobox", optionsKey: "accounts", required: true },
    { name: "category", label: "Category", type: "text", required: true },
    { name: "annualBudget", label: "Annual Budget (INR)", type: "number", required: true },
    { name: "ytdBudget", label: "YTD Budget (INR)", type: "number" },
    { name: "ytdActual", label: "YTD Actual (INR)", type: "number" },
    { name: "committed", label: "Committed (INR)", type: "number" },
    { name: "owner", label: "Owner", type: "text", required: true },
    { name: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "rejected", "locked"] },
    { name: "notes", label: "Notes", type: "textarea", colSpan: 2 },
  ],
  fixedAssets: [
    { name: "code", label: "Asset Code", type: "text", placeholder: "auto-generated" },
    { name: "name", label: "Asset Name", type: "text", required: true, colSpan: 2 },
    { name: "category", label: "Category", type: "select", required: true, options: ["plant-machinery", "tooling", "it-equipment", "vehicles", "furniture", "building"] },
    { name: "costCentreCode", label: "Cost Centre", type: "combobox", optionsKey: "costCentres" },
    { name: "projectCode", label: "Project", type: "combobox", optionsKey: "projects" },
    { name: "acquiredAt", label: "Acquired On", type: "date", required: true },
    { name: "cost", label: "Acquisition Cost (INR)", type: "number", required: true },
    { name: "salvage", label: "Salvage Value (INR)", type: "number" },
    { name: "usefulLifeYears", label: "Useful Life (years)", type: "number", required: true },
    { name: "accumulatedDepreciation", label: "Accumulated Depreciation (INR)", type: "number" },
    { name: "method", label: "Method", type: "select", required: true, options: ["SLM", "WDV"] },
    { name: "location", label: "Location", type: "text", required: true },
    { name: "status", label: "Status", type: "select", options: ["active", "under-maintenance", "disposed"] },
  ],
  disposeAsset: [
    { name: "proceeds", label: "Disposal Proceeds (INR)", type: "number", required: true, colSpan: 2 },
  ],
  closeTasks: [
    { name: "title", label: "Task", type: "text", required: true, colSpan: 2 },
    { name: "period", label: "Period", type: "text", required: true },
    { name: "area", label: "Area", type: "select", required: true, options: ["AR", "AP", "GL", "Bank", "Tax", "Payroll", "Inventory", "Assets", "Reporting"] },
    { name: "owner", label: "Owner", type: "text", required: true },
    { name: "dueAt", label: "Due On", type: "date", required: true },
    { name: "sequence", label: "Sequence", type: "number" },
    { name: "status", label: "Status", type: "select", options: ["pending", "in-progress", "done", "blocked"] },
    { name: "automated", label: "Automated Check", type: "select", options: ["yes", "no"] },
    { name: "note", label: "Note", type: "textarea", colSpan: 2 },
  ],
  allocationRules: [
    { name: "name", label: "Rule Name", type: "text", required: true, colSpan: 2 },
    { name: "code", label: "Code", type: "text", required: true },
    { name: "method", label: "Allocation Method", type: "select", required: true, options: ["direct", "department", "percentage", "man-hour", "quantity", "cost-centre"] },
    { name: "accountCode", label: "Expense Account", type: "text", placeholder: "e.g. 6300" },
    { name: "costCentreCode", label: "Cost Centre", type: "text" },
    { name: "department", label: "Department", type: "text" },
    { name: "expenseCategory", label: "Expense Category", type: "text" },
    { name: "active", label: "Active", type: "select", options: ["yes", "no"] },
    { name: "notes", label: "Notes", type: "textarea", colSpan: 2 },
  ],
  glCoding: [
    { name: "narration", label: "Describe the transaction", type: "textarea", required: true, colSpan: 2, placeholder: "e.g. RTGS to Fanuc for servo drives on PRJ-1021" },
  ],
  matchTxn: [
    { name: "matchedRef", label: "Match to document", type: "combobox", optionsKey: "openDocs", required: true, colSpan: 2 },
  ],
};
