import type { FieldSpec } from "@/components/record-dialog";
import type { EntityKind } from "./types";
import { statusOptions } from "./lifecycle";

const owner: FieldSpec = {
  name: "owner",
  label: "Owner",
  type: "combobox",
  optionsKey: "owners",
  placeholder: "Search sales owner…",
};

const customer: FieldSpec = {
  name: "customerName",
  label: "Customer",
  type: "combobox",
  optionsKey: "customers",
  required: true,
  colSpan: 2,
  placeholder: "Search customer master…",
};

const contact: FieldSpec[] = [
  { name: "contactPerson", label: "Contact Person", type: "text" },
  { name: "contactEmail", label: "Contact Email", type: "email", placeholder: "name@customer.com" },
  { name: "contactPhone", label: "Contact Phone", type: "text", placeholder: "+91 …" },
];

export const CRM_SCHEMAS: Record<EntityKind, FieldSpec[]> = {
  customers: [
    { name: "code", label: "Code", type: "text", required: true, placeholder: "CUS-1000" },
    { name: "name", label: "Name", type: "text", required: true, colSpan: 2 },
    { name: "segment", label: "Segment", type: "select", options: ["OEM", "Tier-1", "Tier-2", "EPC"], required: true },
    { name: "region", label: "Region", type: "select", options: ["North India", "South India", "East India", "West India", "Export"] },
    owner,
    { name: "status", label: "Status", type: "select", options: ["active", "prospect", "inactive"], required: true },
    { name: "annualRevenue", label: "Annual Revenue (INR)", type: "number" },
    { name: "gstin", label: "GSTIN", type: "text", placeholder: "27AAACT1234A1Z5" },
    { name: "paymentTerms", label: "Default Payment Terms", type: "combobox", optionsKey: "paymentTerms", colSpan: 2 },
    { name: "currency", label: "Currency", type: "combobox", optionsKey: "currencies" },
    ...contact,
  ],
  leads: [
    { name: "code", label: "Code", type: "text", required: true },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    customer,
    {
      name: "source",
      label: "Source",
      type: "select",
      options: ["Website", "Referral", "Event", "Outbound", "Partner", "Email", "WhatsApp", "Chatbot", "Campaign", "CSV Import"],
      required: true,
    },
    { name: "campaign", label: "Campaign", type: "text", placeholder: "AutoExpo-2026" },
    owner,
    { name: "estValue", label: "Est. Value (INR)", type: "number" },
    { name: "status", label: "Status", type: "select", options: statusOptions("leads"), required: true },
    { name: "nextFollowUp", label: "Next Follow-up", type: "date" },
    ...contact,
  ],
  opportunities: [
    { name: "code", label: "Code", type: "text", required: true },
    { name: "name", label: "Name", type: "text", required: true, colSpan: 2 },
    customer,
    { name: "value", label: "Value (INR)", type: "number", required: true },
    { name: "probability", label: "Probability %", type: "number" },
    { name: "stage", label: "Stage", type: "select", options: statusOptions("opportunities"), required: true },
    owner,
    { name: "expectedClose", label: "Expected Close", type: "date" },
    { name: "nextFollowUp", label: "Next Follow-up", type: "date" },
    ...contact,
  ],
  rfqs: [
    { name: "code", label: "Code", type: "text", required: true },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    customer,
    { name: "opportunityId", label: "Linked Opportunity", type: "combobox", optionsKey: "opportunities", colSpan: 2, placeholder: "Search opportunity…" },
    { name: "dueDate", label: "Due Date", type: "date" },
    owner,
    { name: "status", label: "Status", type: "select", options: statusOptions("rfqs"), required: true },
    { name: "scope", label: "Scope / Products", type: "textarea" },
    { name: "deliverySchedule", label: "Delivery Schedule", type: "textarea" },
    { name: "commercialTerms", label: "Commercial Terms", type: "textarea" },
    { name: "rfqFile", label: "RFQ Document (PDF / Word / Excel)", type: "file", accept: ".pdf,.doc,.docx,.xls,.xlsx,.eml,.msg", colSpan: 2 },
  ],
  proposals: [
    { name: "code", label: "Code", type: "text", required: true },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    customer,
    { name: "rfqId", label: "Linked RFQ", type: "combobox", optionsKey: "rfqs", colSpan: 2, placeholder: "Search RFQ…" },
    { name: "template", label: "Template", type: "combobox", optionsKey: "proposalTemplates" },
    { name: "version", label: "Version", type: "text", placeholder: "v1.0" },
    { name: "value", label: "Indicative Value (INR)", type: "number" },
    owner,
    { name: "status", label: "Status", type: "select", options: statusOptions("proposals"), required: true },
    { name: "executiveSummary", label: "Executive Summary", type: "textarea" },
    { name: "scope", label: "Scope of Supply", type: "textarea" },
    { name: "deliverables", label: "Deliverables", type: "textarea" },
    { name: "methodology", label: "Implementation Methodology", type: "textarea" },
    { name: "timeline", label: "Timeline", type: "textarea" },
    { name: "assumptions", label: "Assumptions", type: "textarea" },
    { name: "terms", label: "Terms & Conditions", type: "textarea" },
  ],
  quotations: [
    { name: "code", label: "Code", type: "text", required: true },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    customer,
    { name: "proposalId", label: "Linked Proposal", type: "combobox", optionsKey: "proposals", colSpan: 2, placeholder: "Search proposal…" },
    { name: "value", label: "Base Value (INR)", type: "number", required: true },
    { name: "discountPct", label: "Discount %", type: "number" },
    { name: "taxPct", label: "GST %", type: "number", placeholder: "18" },
    { name: "freight", label: "Freight (INR)", type: "number" },
    { name: "marginPct", label: "Margin %", type: "number" },
    { name: "currency", label: "Currency", type: "combobox", optionsKey: "currencies" },
    { name: "paymentTerms", label: "Payment Terms", type: "combobox", optionsKey: "paymentTerms", colSpan: 2 },
    { name: "deliveryTerms", label: "Delivery Terms", type: "combobox", optionsKey: "deliveryTerms" },
    { name: "validity", label: "Valid Until", type: "date" },
    owner,
    { name: "status", label: "Status", type: "select", options: statusOptions("quotations"), required: true },
  ],
  oas: [
    { name: "code", label: "Code", type: "text", required: true },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    customer,
    { name: "quotationId", label: "Linked Quotation", type: "combobox", optionsKey: "quotations", colSpan: 2, placeholder: "Search quotation…" },
    { name: "value", label: "Order Value (INR)", type: "number", required: true },
    { name: "poNumber", label: "Customer PO #", type: "text", required: true },
    { name: "poDate", label: "PO Date", type: "date" },
    owner,
    { name: "status", label: "Status", type: "select", options: statusOptions("oas"), required: true },
  ],
  salesOrders: [
    { name: "code", label: "Code", type: "text", required: true },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    customer,
    { name: "oaId", label: "Linked Order Acceptance", type: "combobox", optionsKey: "oas", colSpan: 2, placeholder: "Search OA…" },
    { name: "value", label: "Order Value (INR)", type: "number", required: true },
    { name: "poNumber", label: "Customer PO #", type: "text" },
    { name: "deliveryDate", label: "Delivery Date", type: "date" },
    { name: "paymentTerms", label: "Payment Terms", type: "combobox", optionsKey: "paymentTerms", colSpan: 2 },
    owner,
    { name: "status", label: "Status", type: "select", options: statusOptions("salesOrders"), required: true },
  ],
};
