import type { FieldSpec } from "@/components/record-dialog";

const st = (name: string, label: string, opts?: Partial<FieldSpec>): FieldSpec => ({ name, label, type: "text", ...opts });
const num = (name: string, label: string): FieldSpec => ({ name, label, type: "number" });
const dt = (name: string, label: string): FieldSpec => ({ name, label, type: "date" });
const sel = (name: string, label: string, options: string[]): FieldSpec => ({ name, label, type: "select", options });
const emp = (name = "empId", label = "Employee"): FieldSpec => ({ name, label, type: "combobox", optionsKey: "employees", required: true });
const dept = (name = "department", label = "Department"): FieldSpec => ({ name, label, type: "combobox", optionsKey: "departments" });

export const WORKFORCE_SCHEMAS: Record<string, FieldSpec[]> = {
  /* Recruitment */
  manpowerPlans: [st("code", "Plan Code"), dept(), st("position", "Position", { required: true }), num("budgeted", "Budgeted"), num("onboard", "On-board"), st("quarter", "Quarter"), st("justification", "Business Justification", { type: "textarea", colSpan: 2 }), sel("status", "Status", ["draft", "pending", "approved", "rejected"])],
  requisitions: [st("position", "Position", { required: true }), dept(), sel("grade", "Grade", ["B1", "B2", "B3", "B4", "B5"]), num("vacancies", "Vacancies"), sel("type", "Employment Type", ["permanent", "contract", "trainee"]), { name: "raisedBy", label: "Raised By", type: "combobox", optionsKey: "approvers" }, dt("raisedOn", "Raised On"), dt("targetDate", "Target Closure"), num("budgetCtc", "Budgeted CTC"), sel("priority", "Priority", ["low", "medium", "high", "critical"]), sel("status", "Status", ["draft", "pending", "approved", "rejected", "closed"])],
  jobPostings: [st("title", "Job Title", { required: true, colSpan: 2 }), { name: "requisition", label: "Requisition", type: "combobox", optionsKey: "requisitions" }, st("channel", "Channel"), dt("postedOn", "Posted On"), num("applications", "Applications"), num("shortlisted", "Shortlisted"), sel("status", "Status", ["draft", "open", "on-hold", "closed"]), st("jd", "Job Description", { type: "textarea", colSpan: 2 })],
  candidates: [st("name", "Candidate Name", { required: true }), st("position", "Position", { required: true }), sel("source", "Source", ["Naukri", "LinkedIn", "Referral", "Walk-in", "Consultant"]), num("experience", "Experience (yrs)"), num("currentCtc", "Current CTC"), num("expectedCtc", "Expected CTC"), num("noticeDays", "Notice (days)"), st("email", "Email", { type: "email" }), st("phone", "Phone"), st("skills", "Key Skills", { colSpan: 2 }), sel("stage", "Stage", ["applied", "screening", "interview", "offer", "hired"]), sel("status", "Status", ["in-progress", "on-hold", "rejected", "hired"])],
  interviews: [{ name: "candidate", label: "Candidate", type: "combobox", optionsKey: "candidates", required: true }, st("round", "Round", { required: true }), { name: "panel", label: "Panel", type: "combobox", optionsKey: "approvers" }, dt("scheduledOn", "Scheduled On"), sel("mode", "Mode", ["In-person", "Video", "Telephonic"]), num("rating", "Rating (1-5)"), sel("recommendation", "Recommendation", ["proceed", "hold", "reject"]), sel("status", "Status", ["scheduled", "completed", "cancelled", "no-show"]), st("feedback", "Feedback", { type: "textarea", colSpan: 2 })],
  offers: [{ name: "candidate", label: "Candidate", type: "combobox", optionsKey: "candidates", required: true }, st("position", "Position"), sel("grade", "Grade", ["B1", "B2", "B3", "B4", "B5"]), num("ctc", "Offered CTC"), dt("joiningDate", "Joining Date"), dt("releasedOn", "Released On"), sel("status", "Status", ["draft", "approved", "released", "withdrawn"]), sel("acceptance", "Acceptance", ["pending", "accepted", "declined"])],
  onboarding: [st("candidate", "New Joiner", { required: true }), dt("joiningDate", "Joining Date"), { name: "buddy", label: "Buddy / Mentor", type: "combobox", optionsKey: "approvers" }, st("documents", "Documents Collected", { placeholder: "8/11" }), sel("itAssets", "IT Assets", ["pending", "issued"]), sel("inductionDone", "Induction", ["yes", "no"]), sel("safetyInduction", "Safety Induction", ["pending", "done"]), num("progress", "Progress %"), sel("status", "Status", ["in-progress", "completed", "on-hold"])],

  /* Performance */
  kpiLibrary: [st("code", "KPI Code"), st("name", "KPI Name", { required: true, colSpan: 2 }), dept(), sel("type", "Measure Type", ["Percentage", "Value", "Timeline", "Quantity", "Score"]), st("uom", "UoM"), num("target", "Target"), num("weightage", "Weightage %"), sel("frequency", "Frequency", ["Monthly", "Quarterly", "Half-Yearly", "Annual"])],
  goals: [emp(), { name: "kpi", label: "KPI", type: "combobox", optionsKey: "kpis", required: true }, st("cycle", "Cycle", { placeholder: "Q3 FY25" }), num("target", "Target"), num("achieved", "Achieved"), num("weightage", "Weightage %"), sel("status", "Status", ["in-progress", "achieved", "at-risk", "missed"])],
  appraisals: [emp(), st("cycle", "Cycle", { placeholder: "Annual FY25" }), num("selfScore", "Self Score"), num("managerScore", "Manager Score"), num("calibratedScore", "Calibrated Score"), sel("rating", "Rating", ["Below", "Meets", "Meets+", "Exceeds", "Outstanding"]), num("incrementPct", "Increment %"), sel("promotion", "Promotion", ["recommended", "not-now"]), sel("newGrade", "Proposed Grade", ["B1", "B2", "B3", "B4", "B5"]), sel("status", "Status", ["self", "manager", "calibration", "closed"])],
  promotions: [emp(), sel("fromGrade", "From Grade", ["B1", "B2", "B3", "B4", "B5"]), sel("toGrade", "To Grade", ["B1", "B2", "B3", "B4", "B5"]), dt("effectiveDate", "Effective Date"), num("currentCtc", "Current CTC"), num("revisedCtc", "Revised CTC"), { name: "recommendedBy", label: "Recommended By", type: "combobox", optionsKey: "approvers" }, sel("status", "Status", ["pending", "approved", "rejected"])],

  /* Learning */
  tni: [sel("level", "Analysis Level", ["Organization", "Department", "Employee"]), st("area", "Training Need", { required: true, colSpan: 2 }), { name: "identifiedBy", label: "Identified By", type: "combobox", optionsKey: "approvers" }, num("employeesImpacted", "Employees Impacted"), sel("priority", "Priority", ["low", "medium", "high", "critical"]), st("source", "Source"), sel("status", "Status", ["pending", "approved", "rejected"])],
  trainingPlans: [st("title", "Programme", { required: true, colSpan: 2 }), { name: "tni", label: "Linked TNI", type: "combobox", optionsKey: "tni" }, { name: "trainer", label: "Trainer", type: "combobox", optionsKey: "trainers" }, st("month", "Planned Month"), num("budget", "Budget (INR)"), num("participants", "Participants"), sel("mode", "Mode", ["Internal", "External", "Online"]), sel("status", "Status", ["draft", "planned", "in-progress", "completed"])],
  competencies: [st("role", "Role", { required: true }), st("competency", "Competency", { required: true }), num("requiredLevel", "Required Level (1-5)"), num("avgLevel", "Current Avg Level"), sel("criticality", "Criticality", ["low", "medium", "high"])],
  trainers: [st("name", "Trainer / Provider", { required: true }), sel("type", "Type", ["Internal", "External"]), st("specialisation", "Specialisation"), num("rating", "Rating"), num("costPerDay", "Cost / Day"), sel("empanelled", "Empanelled", ["yes", "no"])],
  trainingFeedback: [st("training", "Training"), emp(), num("contentScore", "Content (1-5)"), num("trainerScore", "Trainer (1-5)"), num("relevance", "Relevance (1-5)"), num("postTestScore", "Post-test Score"), sel("effectiveness", "Effectiveness", ["low", "medium", "high"]), st("remarks", "Remarks", { type: "textarea", colSpan: 2 })],

  /* Engagement */
  recognitions: [emp(), st("award", "Award", { required: true }), sel("category", "Category", ["Delivery", "Quality", "Safety", "Innovation", "Teamwork"]), st("month", "Period"), { name: "nominatedBy", label: "Nominated By", type: "combobox", optionsKey: "approvers" }, num("rewardValue", "Reward Value (INR)"), sel("status", "Status", ["pending", "approved", "rejected"])],
  wellness: [st("program", "Programme", { required: true, colSpan: 2 }), sel("type", "Type", ["Health", "Wellness", "Recreation", "Retention"]), dt("scheduledOn", "Scheduled On"), st("vendor", "Vendor"), num("participants", "Participants"), num("budget", "Budget (INR)"), sel("status", "Status", ["planned", "in-progress", "completed", "cancelled"])],
  surveys: [st("title", "Survey", { required: true, colSpan: 2 }), st("audience", "Audience"), dt("runOn", "Run On"), num("invited", "Invited"), num("responses", "Responses"), num("avgScore", "Avg Score (1-5)"), num("enps", "eNPS"), sel("status", "Status", ["draft", "in-progress", "completed"])],

  /* Compensation */
  salaryGrades: [st("code", "Grade Code", { required: true }), st("grade", "Grade Name", { required: true }), num("minCtc", "Min CTC"), num("midCtc", "Mid CTC"), num("maxCtc", "Max CTC"), num("benchmark", "Market Benchmark"), sel("positioning", "Positioning", ["below-market", "at-market", "above-market"]), num("headcount", "Headcount")],
  benefits: [st("benefit", "Benefit", { required: true }), st("provider", "Provider"), st("coverage", "Coverage"), num("employerCost", "Employer Cost"), num("employeeCost", "Employee Cost"), dt("renewalDate", "Renewal Date"), sel("status", "Status", ["active", "renewal-due", "lapsed"])],

  /* Administration */
  gatePasses: [sel("type", "Type", ["Returnable", "Non-returnable"]), st("material", "Material", { required: true, colSpan: 2 }), { name: "issuedTo", label: "Issued To", type: "combobox", optionsKey: "approvers" }, st("vendor", "Vendor / Party"), dt("issuedOn", "Issued On"), dt("expectedBack", "Expected Back"), num("value", "Value (INR)"), sel("status", "Status", ["open", "closed", "overdue"])],
  visitors: [st("name", "Visitor Name", { required: true }), st("company", "Company"), { name: "host", label: "Host", type: "combobox", optionsKey: "approvers" }, st("purpose", "Purpose"), dt("date", "Date"), st("inTime", "In Time"), st("outTime", "Out Time"), st("badge", "Badge No."), sel("status", "Status", ["in-premise", "closed"])],
  facilityBookings: [sel("facility", "Facility", ["Board Room", "Training Hall", "Conference Room", "Guest House", "Canteen Hall"]), { name: "bookedBy", label: "Booked By", type: "combobox", optionsKey: "approvers" }, dt("date", "Date"), st("from", "From"), st("to", "To"), st("purpose", "Purpose"), num("attendees", "Attendees"), sel("status", "Status", ["requested", "confirmed", "cancelled"])],
  canteen: [st("month", "Period", { required: true }), st("vendor", "Vendor"), num("mealsServed", "Meals Served"), num("ratePerMeal", "Rate / Meal"), num("amount", "Amount"), num("subsidy", "Company Subsidy"), num("hygieneScore", "Hygiene Score"), sel("status", "Status", ["pending", "verified", "paid"])],
  transport: [st("code", "Vehicle / Route Code"), sel("type", "Type", ["Employee Bus", "Cab", "Goods Vehicle"]), st("route", "Route", { colSpan: 2 }), st("vendor", "Vendor"), num("capacity", "Capacity"), num("occupancy", "Avg Occupancy"), num("monthlyCost", "Monthly Cost"), num("fuelLtr", "Fuel (Ltr)"), sel("status", "Status", ["active", "suspended"])],
  housekeeping: [st("area", "Area", { required: true }), st("contractor", "Contractor"), num("headcount", "Headcount"), st("frequency", "Frequency"), num("auditScore", "Audit Score"), num("monthlyCost", "Monthly Cost"), sel("status", "Status", ["active", "suspended"])],
  stationery: [st("code", "Item Code"), st("item", "Item", { required: true }), sel("category", "Category", ["Stationery", "Safety material", "Consumable", "Housekeeping"]), num("opening", "Opening"), num("issued", "Issued"), num("closing", "Closing"), num("reorder", "Reorder Level"), num("unitCost", "Unit Cost")],
  utilityBills: [sel("utility", "Utility", ["Electricity", "Water", "Gas", "Internet", "Telephone"]), st("period", "Period"), st("vendor", "Provider"), num("units", "Units"), num("amount", "Amount"), dt("dueDate", "Due Date"), sel("status", "Status", ["pending", "verified", "paid", "overdue"])],
  adminInvoices: [st("vendor", "Vendor", { required: true }), sel("category", "Category", ["Housekeeping", "Transport", "Canteen", "Utilities", "Facility", "Stationery", "Others"]), dt("invoiceDate", "Invoice Date"), num("amount", "Amount"), st("poRef", "PO Reference"), sel("threeWayMatch", "3-Way Match", ["matched", "variance", "not-checked"]), sel("status", "Status", ["pending", "approved", "rejected", "paid"])],
  adminQuotes: [st("code", "RFQ Code"), st("requirement", "Requirement", { required: true, colSpan: 2 }), st("vendor", "Vendor", { required: true }), num("quoteAmount", "Quote Amount"), num("deliveryDays", "Delivery (days)"), num("rating", "Vendor Rating"), sel("recommended", "Recommended", ["yes", "no"]), sel("status", "Status", ["requested", "received", "awarded", "rejected"])],
  adminStock: [sel("category", "Category", ["Scrap", "Hazardous waste", "General waste", "Consumable"]), st("item", "Item", { required: true }), num("quantity", "Quantity"), st("uom", "UoM"), st("disposalVendor", "Disposal Vendor"), num("realisation", "Realisation (INR)"), dt("disposedOn", "Disposal Date"), sel("status", "Status", ["scheduled", "disposed", "pending"])],

  /* Travel & expense */
  travelRequests: [emp(), st("purpose", "Purpose", { required: true, colSpan: 2 }), st("destination", "Destination"), dt("fromDate", "From"), dt("toDate", "To"), sel("mode", "Mode", ["Flight", "Train", "Cab", "Bus", "Own vehicle"]), num("estimatedCost", "Estimated Cost"), num("advance", "Advance Requested"), sel("status", "Status", ["draft", "pending", "approved", "rejected", "completed"])],
  expenseClaims: [emp(), { name: "travelRef", label: "Travel Reference", type: "combobox", optionsKey: "travel" }, sel("category", "Category", ["Travel", "Local conveyance", "Lodging", "Meals", "Client entertainment", "Others"]), dt("claimDate", "Claim Date"), num("amount", "Amount"), num("receipts", "Receipts Attached"), sel("policyFlag", "Policy Check", ["within-policy", "exceeds-limit", "duplicate-suspect", "missing-receipt"]), sel("status", "Status", ["pending", "approved", "rejected", "paid"])],
  bookings: [sel("type", "Booking Type", ["Flight", "Hotel", "Train", "Cab", "Bus"]), { name: "travelRef", label: "Travel Reference", type: "combobox", optionsKey: "travel" }, st("vendor", "Vendor"), st("detail", "Details", { colSpan: 2 }), num("amount", "Amount"), dt("bookedOn", "Booked On"), sel("status", "Status", ["hold", "confirmed", "cancelled"])],

  /* Safety */
  incidents: [sel("type", "Incident Type", ["Near miss", "First aid", "Medical treatment", "Lost time injury", "Property damage", "Environmental"]), st("area", "Area", { required: true }), dt("date", "Date"), sel("severity", "Severity", ["low", "medium", "high", "critical"]), st("injured", "Person Involved"), num("lostDays", "Lost Days"), st("rootCause", "Root Cause", { type: "textarea", colSpan: 2 }), st("capa", "Corrective Action", { type: "textarea", colSpan: 2 }), sel("status", "Status", ["open", "in-progress", "closed"])],
  nearMisses: [st("area", "Area", { required: true }), dt("date", "Date"), st("description", "Observation", { type: "textarea", colSpan: 2 }), { name: "reportedBy", label: "Reported By", type: "combobox", optionsKey: "approvers" }, sel("potential", "Potential Severity", ["low", "medium", "high", "critical"]), st("action", "Action Taken", { colSpan: 2 }), sel("status", "Status", ["open", "in-progress", "closed"])],
  hazards: [st("hazard", "Hazard", { required: true, colSpan: 2 }), st("area", "Area"), sel("category", "Category", ["Mechanical", "Electrical", "Fire", "Chemical", "Ergonomic", "Occupational health", "Operational"]), num("likelihood", "Likelihood (1-5)"), num("severity", "Severity (1-5)"), st("control", "Control Measure", { colSpan: 2 }), { name: "owner", label: "Owner", type: "combobox", optionsKey: "approvers" }, sel("status", "Status", ["open", "in-progress", "mitigated"])],
  risks: [st("risk", "Risk", { required: true, colSpan: 2 }), st("category", "Category"), num("inherentScore", "Inherent Score"), num("residualScore", "Residual Score"), st("mitigation", "Mitigation", { type: "textarea", colSpan: 2 }), { name: "owner", label: "Owner", type: "combobox", optionsKey: "approvers" }, dt("reviewDate", "Next Review"), sel("status", "Status", ["open", "in-progress", "mitigated", "closed"])],
  safetyAudits: [st("type", "Audit Type", { required: true }), st("area", "Area"), st("auditor", "Auditor"), dt("date", "Date"), num("findings", "Findings"), num("closed", "Closed"), num("score", "Score %"), st("standard", "Standard"), sel("status", "Status", ["planned", "in-progress", "closed"])],

  /* Compliance */
  complianceItems: [sel("type", "Compliance Type", ["Statutory", "Company", "Customer", "Vendor"]), st("requirement", "Requirement", { required: true, colSpan: 2 }), st("authority", "Authority"), sel("frequency", "Frequency", ["Monthly", "Quarterly", "Half-yearly", "Annual", "One-time"]), { name: "owner", label: "Owner", type: "combobox", optionsKey: "approvers" }, dt("dueDate", "Next Due"), dt("lastFiled", "Last Filed"), sel("status", "Status", ["pending", "filed", "overdue", "waived"])],
  auditTracking: [st("audit", "Audit", { required: true, colSpan: 2 }), st("auditor", "Auditor"), dt("date", "Audit Date"), num("ncrs", "NCRs Raised"), num("closed", "NCRs Closed"), dt("dueDate", "Closure Due"), sel("status", "Status", ["planned", "in-progress", "closed"])],

  /* Documents */
  documents: [st("code", "Document No."), st("title", "Title", { required: true, colSpan: 2 }), sel("category", "Category", ["HR Policy", "Safety", "Compliance", "Administration", "Quality", "Contract"]), { name: "owner", label: "Owner", type: "combobox", optionsKey: "approvers" }, st("version", "Version"), sel("label", "Label", ["Internal", "Controlled", "Confidential", "Statutory", "Archive"]), dt("reviewDate", "Next Review"), st("retention", "Retention"), st("storage", "Server Path", { colSpan: 2 }), sel("status", "Status", ["draft", "approved", "review-due", "deletion-requested", "archived"]), { name: "file", label: "Attach File", type: "file", colSpan: 2 }],
  dataGovernance: [st("folder", "Folder", { required: true }), st("convention", "Naming Convention", { colSpan: 2 }), { name: "owner", label: "Owner", type: "combobox", optionsKey: "approvers" }, dt("lastReview", "Last Review"), dt("nextReview", "Next Review"), st("archivePolicy", "Archive Policy", { colSpan: 2 }), sel("status", "Status", ["compliant", "review-due", "non-compliant"])],

  /* Contract labour */
  contractors: [st("contractor", "Contractor", { required: true }), sel("category", "Category", ["Housekeeping", "Security", "Operational labour", "Canteen", "Transport"]), st("licenceNo", "Labour Licence No."), dt("licenceExpiry", "Licence Expiry"), num("workers", "Workers Deployed"), sel("pfEsicCompliant", "PF/ESIC Compliant", ["yes", "partial", "no"]), num("performanceScore", "Performance Score"), sel("status", "Status", ["active", "licence-expired", "blacklisted", "suspended"])],
  contractWorkers: [st("name", "Worker Name", { required: true }), { name: "contractor", label: "Contractor", type: "combobox", optionsKey: "contractors" }, st("skill", "Skill"), st("area", "Deployment Area"), num("daysWorked", "Days Worked"), num("rate", "Daily Rate"), sel("inductionDone", "Safety Induction", ["yes", "no"]), sel("status", "Status", ["active", "released"])],
  contractBills: [{ name: "contractor", label: "Contractor", type: "combobox", optionsKey: "contractors", required: true }, st("period", "Period"), num("manDays", "Man-days"), num("amount", "Bill Amount"), num("pfEsic", "PF / ESIC"), sel("complianceDocs", "Compliance Docs", ["submitted", "missing", "partial"]), sel("status", "Status", ["pending", "approved", "on-hold", "paid"])],
};
