import {
  Building2,
  Truck,
  Package,
  UserSquare2,
  Cog,
  Ruler,
  Receipt,
  Percent,
  CreditCard,
  Coins,
  Tags,
  Warehouse,
  Grid3x3,
  Wallet,
  BookOpen,
  Network,
  BadgeCheck,
} from "lucide-react";
import type { MasterDef } from "./types";


/**
 * Every master inherits the same architecture — list, create, edit, view,
 * approvals, activity, attachments, search, filters, import, export, bulk
 * upload — by describing itself here.
 */

const COUNTRIES = [
  { label: "India", value: "IN" },
  { label: "USA", value: "US" },
  { label: "Germany", value: "DE" },
  { label: "Japan", value: "JP" },
  { label: "UK", value: "GB" },
];

export const MASTERS: MasterDef[] = [
  {
    key: "customers",
    name: "Customer",
    pluralName: "Customers",
    description: "OEMs, tier-1 suppliers and end clients.",
    icon: Building2,
    accentClass: "bg-primary/10 text-primary",
    codePrefix: "CUS",
    requiresApproval: true,
    approvalSteps: ["Sales Review", "Finance Review"],
    titleField: "name",
    fields: [
      { key: "name", label: "Legal Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "short_name", label: "Short Name", type: "text", showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "segment", label: "Segment", type: "select", options: [
        { label: "OEM", value: "OEM" },
        { label: "Tier 1", value: "TIER1" },
        { label: "Tier 2", value: "TIER2" },
        { label: "Aftermarket", value: "AFTER" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "country", label: "Country", type: "select", options: COUNTRIES, showInList: true, filterable: true, importable: true, group: "Address" },
      { key: "gstin", label: "GSTIN / Tax ID", type: "text", importable: true, group: "Compliance" },
      { key: "credit_limit", label: "Credit Limit", type: "currency", importable: true, group: "Commercial" },
      { key: "payment_terms", label: "Payment Terms", type: "text", placeholder: "e.g. Net 45", importable: true, group: "Commercial" },
      { key: "email", label: "Primary Email", type: "email", importable: true, group: "Contact" },
      { key: "phone", label: "Primary Phone", type: "phone", importable: true, group: "Contact" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
      { key: "notes", label: "Notes", type: "textarea", span: 2, group: "Status" },
    ],
  },
  {
    key: "suppliers",
    name: "Supplier",
    pluralName: "Suppliers",
    description: "Raw material and component vendors.",
    icon: Truck,
    accentClass: "bg-info/10 text-info",
    codePrefix: "SUP",
    requiresApproval: true,
    approvalSteps: ["Purchase Review", "Quality Review", "Finance Review"],
    titleField: "name",
    fields: [
      { key: "name", label: "Supplier Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "category", label: "Category", type: "select", options: [
        { label: "Raw Material", value: "RAW" },
        { label: "Consumables", value: "CONS" },
        { label: "Services", value: "SVC" },
        { label: "Capital Goods", value: "CAP" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "country", label: "Country", type: "select", options: COUNTRIES, showInList: true, filterable: true, importable: true, group: "Address" },
      { key: "gstin", label: "GSTIN / Tax ID", type: "text", importable: true, group: "Compliance" },
      { key: "rating", label: "Rating", type: "select", options: [
        { label: "A", value: "A" }, { label: "B", value: "B" }, { label: "C", value: "C" },
      ], showInList: true, filterable: true, importable: true, group: "Performance" },
      { key: "lead_time_days", label: "Lead Time (days)", type: "number", importable: true, group: "Performance" },
      { key: "email", label: "Primary Email", type: "email", importable: true, group: "Contact" },
      { key: "phone", label: "Primary Phone", type: "phone", importable: true, group: "Contact" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "items",
    name: "Item",
    pluralName: "Items",
    description: "Raw materials, components, sub-assemblies and finished goods.",
    icon: Package,
    accentClass: "bg-accent/15 text-accent-foreground",
    codePrefix: "ITM",
    requiresApproval: false,
    titleField: "description",
    fields: [
      { key: "description", label: "Description", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "General", span: 2 },
      { key: "category", label: "Category", type: "select", options: [
        { label: "Raw Material", value: "RAW" },
        { label: "Component", value: "COMP" },
        { label: "Sub-Assembly", value: "SUB" },
        { label: "Finished Good", value: "FG" },
      ], required: true, showInList: true, filterable: true, importable: true, group: "General" },
      { key: "uom", label: "Unit of Measure", type: "select", options: [
        { label: "Each", value: "EA" }, { label: "Kg", value: "KG" }, { label: "Meter", value: "M" }, { label: "Litre", value: "L" },
      ], required: true, showInList: true, importable: true, group: "General" },
      { key: "hsn_code", label: "HSN Code", type: "text", importable: true, group: "Compliance" },
      { key: "std_cost", label: "Standard Cost", type: "currency", showInList: true, importable: true, group: "Costing" },
      { key: "reorder_level", label: "Reorder Level", type: "number", importable: true, group: "Inventory" },
      { key: "shelf_life_days", label: "Shelf Life (days)", type: "number", importable: true, group: "Inventory" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "employees",
    name: "Employee",
    pluralName: "Employees",
    description: "Workforce master across departments.",
    icon: UserSquare2,
    accentClass: "bg-success/10 text-success",
    codePrefix: "EMP",
    requiresApproval: true,
    approvalSteps: ["HR Review"],
    titleField: "full_name",
    fields: [
      { key: "full_name", label: "Full Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "department", label: "Department", type: "select", options: [
        { label: "Engineering", value: "ENG" },
        { label: "Production", value: "PROD" },
        { label: "Quality", value: "QC" },
        { label: "Sales", value: "SALES" },
        { label: "Finance", value: "FIN" },
        { label: "HR", value: "HR" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "designation", label: "Designation", type: "text", showInList: true, importable: true, group: "Identity" },
      { key: "date_of_joining", label: "Date of Joining", type: "date", importable: true, group: "Employment" },
      { key: "email", label: "Work Email", type: "email", importable: true, group: "Contact" },
      { key: "phone", label: "Phone", type: "phone", importable: true, group: "Contact" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "machines",
    name: "Machine",
    pluralName: "Machines",
    description: "Shop-floor assets, cells and stations.",
    icon: Cog,
    accentClass: "bg-warning/10 text-warning",
    codePrefix: "MCH",
    requiresApproval: false,
    titleField: "name",
    fields: [
      { key: "name", label: "Machine Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "type", label: "Type", type: "select", options: [
        { label: "Weld Cell", value: "WELD" },
        { label: "Press", value: "PRESS" },
        { label: "CNC", value: "CNC" },
        { label: "Assembly", value: "ASM" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "location", label: "Location", type: "text", showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "capacity_per_hour", label: "Capacity / Hour", type: "number", importable: true, group: "Capability" },
      { key: "commissioned_on", label: "Commissioned On", type: "date", importable: true, group: "Lifecycle" },
      { key: "active", label: "Operational", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* Commercial & Compliance                                            */
  /* ------------------------------------------------------------------ */
  {
    key: "uom",
    name: "Unit of Measure",
    pluralName: "Units of Measure",
    description: "Base and derived measurement units with conversions.",
    icon: Ruler,
    accentClass: "bg-info/10 text-info",
    codePrefix: "UOM",
    requiresApproval: false,
    titleField: "name",
    fields: [
      { key: "name", label: "Unit Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "symbol", label: "Symbol", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "dimension", label: "Dimension", type: "select", options: [
        { label: "Quantity", value: "QTY" }, { label: "Weight", value: "WEIGHT" },
        { label: "Length", value: "LENGTH" }, { label: "Volume", value: "VOLUME" },
        { label: "Area", value: "AREA" }, { label: "Time", value: "TIME" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "base_unit", label: "Base Unit", type: "text", showInList: true, importable: true, group: "Conversion" },
      { key: "conversion_factor", label: "Conversion Factor", type: "number", defaultValue: 1, importable: true, group: "Conversion" },
      { key: "decimal_places", label: "Decimal Places", type: "number", defaultValue: 2, importable: true, group: "Conversion" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "hsn-codes",
    name: "HSN / SAC Code",
    pluralName: "HSN & SAC Codes",
    description: "Harmonised codes mapped to default GST rates.",
    icon: Receipt,
    accentClass: "bg-warning/10 text-warning",
    codePrefix: "HSN",
    requiresApproval: true,
    approvalSteps: ["Finance Review"],
    titleField: "description",
    fields: [
      { key: "hsn", label: "HSN / SAC", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "description", label: "Description", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "supply_type", label: "Supply Type", type: "select", options: [
        { label: "Goods", value: "GOODS" }, { label: "Service", value: "SERVICE" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "chapter", label: "Chapter", type: "text", importable: true, group: "Classification" },
      { key: "gst_rate", label: "Default GST Rate (%)", type: "number", showInList: true, filterable: true, importable: true, group: "Taxation" },
      { key: "cess_rate", label: "Cess (%)", type: "number", importable: true, group: "Taxation" },
      { key: "uom", label: "Reporting UoM", type: "text", importable: true, group: "Taxation" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "gst-rates",
    name: "GST Rate",
    pluralName: "GST Rates",
    description: "Slab definitions with CGST / SGST / IGST splits.",
    icon: Percent,
    accentClass: "bg-destructive/10 text-destructive",
    codePrefix: "GST",
    requiresApproval: true,
    approvalSteps: ["Finance Review"],
    titleField: "name",
    fields: [
      { key: "name", label: "Slab Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "rate", label: "Total Rate (%)", type: "number", required: true, showInList: true, filterable: true, importable: true, group: "Split" },
      { key: "cgst", label: "CGST (%)", type: "number", showInList: true, importable: true, group: "Split" },
      { key: "sgst", label: "SGST (%)", type: "number", showInList: true, importable: true, group: "Split" },
      { key: "igst", label: "IGST (%)", type: "number", showInList: true, importable: true, group: "Split" },
      { key: "cess", label: "Cess (%)", type: "number", importable: true, group: "Split" },
      { key: "effective_from", label: "Effective From", type: "date", importable: true, group: "Validity" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "payment-terms",
    name: "Payment Term",
    pluralName: "Payment Terms",
    description: "Credit periods, milestones and early-payment discounts.",
    icon: CreditCard,
    accentClass: "bg-primary/10 text-primary",
    codePrefix: "PT",
    requiresApproval: false,
    titleField: "name",
    fields: [
      { key: "name", label: "Term Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "applies_to", label: "Applies To", type: "select", options: [
        { label: "Customer", value: "CUSTOMER" }, { label: "Supplier", value: "SUPPLIER" }, { label: "Both", value: "BOTH" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "credit_days", label: "Credit Days", type: "number", showInList: true, importable: true, group: "Commercial" },
      { key: "advance_pct", label: "Advance (%)", type: "number", showInList: true, importable: true, group: "Commercial" },
      { key: "on_delivery_pct", label: "On Delivery (%)", type: "number", importable: true, group: "Commercial" },
      { key: "retention_pct", label: "Retention (%)", type: "number", importable: true, group: "Commercial" },
      { key: "discount_pct", label: "Early Payment Discount (%)", type: "number", importable: true, group: "Commercial" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "currencies",
    name: "Currency",
    pluralName: "Currencies",
    description: "Transaction currencies and exchange rates.",
    icon: Coins,
    accentClass: "bg-success/10 text-success",
    codePrefix: "CUR",
    requiresApproval: false,
    titleField: "name",
    fields: [
      { key: "iso_code", label: "ISO Code", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "name", label: "Currency Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "symbol", label: "Symbol", type: "text", showInList: true, importable: true, group: "Identity" },
      { key: "exchange_rate", label: "Rate to INR", type: "number", showInList: true, importable: true, group: "Rate" },
      { key: "rate_date", label: "Rate As Of", type: "date", importable: true, group: "Rate" },
      { key: "is_base", label: "Base Currency", type: "boolean", defaultValue: false, filterable: true, group: "Rate" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "item-categories",
    name: "Item Category",
    pluralName: "Item Categories",
    description: "Classification tree for materials and finished goods.",
    icon: Tags,
    accentClass: "bg-accent/15 text-accent-foreground",
    codePrefix: "ICT",
    requiresApproval: false,
    titleField: "name",
    fields: [
      { key: "name", label: "Category Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "parent", label: "Parent Category", type: "text", showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "valuation_method", label: "Valuation Method", type: "select", options: [
        { label: "Moving Average", value: "MAVG" }, { label: "FIFO", value: "FIFO" }, { label: "Standard Cost", value: "STD" },
      ], showInList: true, filterable: true, importable: true, group: "Costing" },
      { key: "default_hsn", label: "Default HSN", type: "text", importable: true, group: "Compliance" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* Inventory                                                          */
  /* ------------------------------------------------------------------ */
  {
    key: "warehouses",
    name: "Warehouse",
    pluralName: "Warehouses",
    description: "Stores, yards and plant-side stocking locations.",
    icon: Warehouse,
    accentClass: "bg-info/10 text-info",
    codePrefix: "WH",
    requiresApproval: true,
    approvalSteps: ["Stores Review"],
    titleField: "name",
    fields: [
      { key: "name", label: "Warehouse Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "type", label: "Type", type: "select", options: [
        { label: "Raw Material", value: "RM" }, { label: "WIP", value: "WIP" },
        { label: "Finished Goods", value: "FG" }, { label: "Scrap", value: "SCRAP" },
        { label: "Bonded", value: "BOND" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "plant", label: "Plant / Branch", type: "text", showInList: true, filterable: true, importable: true, group: "Location" },
      { key: "address", label: "Address", type: "textarea", span: 2, group: "Location" },
      { key: "gstin", label: "GSTIN", type: "text", importable: true, group: "Compliance" },
      { key: "incharge", label: "Store In-charge", type: "text", showInList: true, importable: true, group: "Ownership" },
      { key: "capacity_sqm", label: "Capacity (sqm)", type: "number", importable: true, group: "Capacity" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "storage-bins",
    name: "Storage Bin",
    pluralName: "Storage Bins",
    description: "Rack, row and bin level addressing inside a warehouse.",
    icon: Grid3x3,
    accentClass: "bg-warning/10 text-warning",
    codePrefix: "BIN",
    requiresApproval: false,
    titleField: "name",
    fields: [
      { key: "name", label: "Bin Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity" },
      { key: "warehouse", label: "Warehouse", type: "text", required: true, showInList: true, filterable: true, searchable: true, importable: true, group: "Identity" },
      { key: "zone", label: "Zone", type: "text", showInList: true, filterable: true, importable: true, group: "Address" },
      { key: "rack", label: "Rack", type: "text", importable: true, group: "Address" },
      { key: "level", label: "Level", type: "text", importable: true, group: "Address" },
      { key: "bin_type", label: "Bin Type", type: "select", options: [
        { label: "Pallet", value: "PALLET" }, { label: "Shelf", value: "SHELF" },
        { label: "Floor", value: "FLOOR" }, { label: "Cage", value: "CAGE" },
      ], showInList: true, filterable: true, importable: true, group: "Address" },
      { key: "max_weight_kg", label: "Max Weight (kg)", type: "number", importable: true, group: "Capacity" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },

  /* ------------------------------------------------------------------ */
  /* Organisation & Finance                                             */
  /* ------------------------------------------------------------------ */
  {
    key: "cost-centres",
    name: "Cost Centre",
    pluralName: "Cost Centres",
    description: "Cost pools for project, plant and overhead accounting.",
    icon: Wallet,
    accentClass: "bg-primary/10 text-primary",
    codePrefix: "CC",
    requiresApproval: true,
    approvalSteps: ["Finance Review"],
    titleField: "name",
    fields: [
      { key: "name", label: "Cost Centre Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "type", label: "Type", type: "select", options: [
        { label: "Production", value: "PROD" }, { label: "Project", value: "PROJ" },
        { label: "Overhead", value: "OH" }, { label: "Sales", value: "SALES" },
        { label: "R&D", value: "RND" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "parent", label: "Parent Cost Centre", type: "text", importable: true, group: "Identity" },
      { key: "owner", label: "Owner", type: "text", showInList: true, importable: true, group: "Ownership" },
      { key: "annual_budget", label: "Annual Budget", type: "currency", showInList: true, importable: true, group: "Budget" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "ledger-groups",
    name: "Ledger Group",
    pluralName: "Ledger Groups",
    description: "Chart-of-accounts groupings used across statements.",
    icon: BookOpen,
    accentClass: "bg-success/10 text-success",
    codePrefix: "LG",
    requiresApproval: true,
    approvalSteps: ["Finance Review"],
    titleField: "name",
    fields: [
      { key: "name", label: "Group Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "nature", label: "Nature", type: "select", options: [
        { label: "Asset", value: "ASSET" }, { label: "Liability", value: "LIABILITY" },
        { label: "Equity", value: "EQUITY" }, { label: "Income", value: "INCOME" },
        { label: "Expense", value: "EXPENSE" },
      ], required: true, showInList: true, filterable: true, importable: true, group: "Classification" },
      { key: "parent", label: "Parent Group", type: "text", showInList: true, importable: true, group: "Classification" },
      { key: "statement", label: "Appears In", type: "select", options: [
        { label: "Balance Sheet", value: "BS" }, { label: "Profit & Loss", value: "PL" },
      ], showInList: true, filterable: true, importable: true, group: "Classification" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "departments",
    name: "Department",
    pluralName: "Departments",
    description: "Organisational units used for routing and approvals.",
    icon: Network,
    accentClass: "bg-info/10 text-info",
    codePrefix: "DEP",
    requiresApproval: false,
    titleField: "name",
    fields: [
      { key: "name", label: "Department Name", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "head", label: "Department Head", type: "text", showInList: true, importable: true, group: "Ownership" },
      { key: "cost_centre", label: "Cost Centre", type: "text", showInList: true, importable: true, group: "Ownership" },
      { key: "location", label: "Location", type: "text", showInList: true, filterable: true, importable: true, group: "Location" },
      { key: "headcount", label: "Headcount", type: "number", importable: true, group: "Capacity" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
  {
    key: "designations",
    name: "Designation",
    pluralName: "Designations",
    description: "Job titles mapped to grades and approval authority.",
    icon: BadgeCheck,
    accentClass: "bg-accent/15 text-accent-foreground",
    codePrefix: "DSG",
    requiresApproval: false,
    titleField: "title",
    fields: [
      { key: "title", label: "Designation", type: "text", required: true, showInList: true, searchable: true, importable: true, group: "Identity", span: 2 },
      { key: "grade", label: "Grade / Band", type: "select", options: [
        { label: "B1", value: "B1" }, { label: "B2", value: "B2" }, { label: "B3", value: "B3" },
        { label: "B4", value: "B4" }, { label: "B5", value: "B5" },
      ], showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "department", label: "Department", type: "text", showInList: true, filterable: true, importable: true, group: "Identity" },
      { key: "reports_to", label: "Reports To", type: "text", importable: true, group: "Hierarchy" },
      { key: "approval_limit", label: "Approval Limit", type: "currency", showInList: true, importable: true, group: "Authority" },
      { key: "active", label: "Active", type: "boolean", defaultValue: true, filterable: true, group: "Status" },
    ],
  },
];

/** Domain grouping used on the Master Data index page. */
export const MASTER_GROUPS: { label: string; description: string; keys: string[] }[] = [
  {
    label: "Core Business",
    description: "Trading partners, materials, people and assets.",
    keys: ["customers", "suppliers", "items", "employees", "machines"],
  },
  {
    label: "Commercial & Compliance",
    description: "Units, tax codes, rates, terms and currencies.",
    keys: ["uom", "hsn-codes", "gst-rates", "payment-terms", "currencies", "item-categories"],
  },
  {
    label: "Inventory",
    description: "Stocking locations and bin-level addressing.",
    keys: ["warehouses", "storage-bins"],
  },
  {
    label: "Organisation & Finance",
    description: "Cost centres, ledger groups and org structure.",
    keys: ["cost-centres", "ledger-groups", "departments", "designations"],
  },
];


export function findMaster(key: string) {
  return MASTERS.find((m) => m.key === key) ?? null;
}
