import type { FieldSpec } from "@/components/record-dialog";

/** Metadata-driven forms for every GST & compliance sub-module. */
export const GST_SCHEMAS: Record<string, FieldSpec[]> = {
  registrations: [
    { name: "gstin", label: "GSTIN", type: "text", required: true, placeholder: "27AAFCF1234M1ZP" },
    { name: "legalName", label: "Legal name", type: "text", required: true, colSpan: 2 },
    { name: "tradeName", label: "Trade name", type: "text", colSpan: 2 },
    { name: "state", label: "State", type: "text", required: true },
    { name: "type", label: "Registration type", type: "select", options: ["Regular", "SEZ", "ISD", "Casual"], required: true },
    { name: "registeredOn", label: "Registered on", type: "date", required: true },
    { name: "status", label: "Status", type: "select", options: ["active", "suspended"] },
  ],
  returns: [
    { name: "gstin", label: "GSTIN", type: "combobox", optionsKey: "gstins", required: true },
    { name: "period", label: "Period (YYYY-MM)", type: "text", required: true, placeholder: "2024-09" },
    { name: "type", label: "Return type", type: "select", options: ["GSTR-1", "GSTR-3B", "GSTR-2B", "GSTR-9"], required: true },
    { name: "dueDate", label: "Due date", type: "date", required: true },
    { name: "taxableValue", label: "Taxable value", type: "number", required: true },
    { name: "igst", label: "IGST", type: "number" },
    { name: "cgst", label: "CGST", type: "number" },
    { name: "sgst", label: "SGST", type: "number" },
    { name: "cess", label: "Cess", type: "number" },
    { name: "status", label: "Status", type: "select", options: ["not-started", "in-progress", "ready", "filed", "late"] },
  ],
  eInvoices: [
    { name: "invoiceNo", label: "Invoice no.", type: "text", required: true },
    { name: "date", label: "Invoice date", type: "date", required: true },
    { name: "customer", label: "Customer", type: "combobox", optionsKey: "customers", required: true, colSpan: 2 },
    { name: "gstin", label: "Customer GSTIN", type: "text", required: true },
    { name: "taxableValue", label: "Taxable value", type: "number", required: true },
    { name: "totalTax", label: "Total tax", type: "number", required: true },
    { name: "status", label: "Status", type: "select", options: ["pending", "generated", "cancelled", "failed"] },
  ],
  eWayBills: [
    { name: "ewbNo", label: "e-Way bill no.", type: "text", required: true },
    { name: "invoiceNo", label: "Invoice no.", type: "combobox", optionsKey: "invoices", required: true },
    { name: "date", label: "Date", type: "date", required: true },
    { name: "fromPlace", label: "From", type: "text", required: true },
    { name: "toPlace", label: "To", type: "text", required: true },
    { name: "distanceKm", label: "Distance (km)", type: "number", required: true },
    { name: "vehicleNo", label: "Vehicle no.", type: "text", required: true },
    { name: "transporter", label: "Transporter", type: "text", required: true },
    { name: "validUpto", label: "Valid upto", type: "date", required: true },
    { name: "value", label: "Consignment value", type: "number", required: true },
    { name: "status", label: "Status", type: "select", options: ["active", "expired", "cancelled"] },
  ],
  itc: [
    { name: "supplier", label: "Supplier", type: "combobox", optionsKey: "suppliers", required: true, colSpan: 2 },
    { name: "gstin", label: "Supplier GSTIN", type: "text", required: true },
    { name: "invoiceNo", label: "Invoice no.", type: "text", required: true },
    { name: "date", label: "Invoice date", type: "date", required: true },
    { name: "bookValue", label: "Value as per books", type: "number" },
    { name: "gstr2bValue", label: "Value as per GSTR-2B", type: "number" },
    { name: "itcClaimable", label: "ITC claimable", type: "number" },
    { name: "match", label: "Match status", type: "select", options: ["matched", "mismatch", "missing-in-2b", "missing-in-books"] },
  ],
  hsn: [
    { name: "hsn", label: "HSN / SAC", type: "combobox", optionsKey: "hsnCodes", required: true },
    { name: "description", label: "Description", type: "text", required: true, colSpan: 2 },
    { name: "uom", label: "UoM", type: "select", options: ["EA", "KG", "MTR", "SET", "LOT", "HRS"], required: true },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "taxableValue", label: "Taxable value", type: "number", required: true },
    { name: "rate", label: "GST rate (%)", type: "select", options: ["0", "5", "12", "18", "28"], required: true },
    { name: "igst", label: "IGST", type: "number" },
    { name: "cgst", label: "CGST", type: "number" },
    { name: "sgst", label: "SGST", type: "number" },
  ],
  vehicleUpdate: [
    { name: "vehicleNo", label: "New vehicle no.", type: "text", required: true },
    { name: "validUpto", label: "Extend validity to", type: "date", required: true },
    { name: "reason", label: "Reason", type: "textarea", colSpan: 2 },
  ],
};
