import type { FieldSpec } from "@/components/record-dialog";

export const QUALITY_SCHEMAS: Record<string, FieldSpec[]> = {
  checklists: [
    { name: "code", label: "Plan Code", type: "text", placeholder: "auto-generated" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "stage", label: "Stage", type: "select", required: true, options: ["incoming", "in-process", "final"] },
    { name: "itemCode", label: "Item Code", type: "combobox", optionsKey: "items" },
    { name: "itemDescription", label: "Item Description", type: "text", colSpan: 2 },
    { name: "revision", label: "Revision", type: "text", required: true, placeholder: "R1" },
    { name: "owner", label: "Owner", type: "combobox", optionsKey: "inspectors", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "approved", "obsolete"] },
  ],
  checks: [
    { name: "parameter", label: "Parameter", type: "text", required: true, colSpan: 2 },
    { name: "type", label: "Check Type", type: "select", required: true, options: ["dimensional", "visual", "functional", "material", "torque", "weld"] },
    { name: "method", label: "Method / Instrument", type: "combobox", optionsKey: "gauges", required: true },
    { name: "nominal", label: "Nominal", type: "text" },
    { name: "unit", label: "Unit", type: "text" },
    { name: "lsl", label: "LSL", type: "number" },
    { name: "usl", label: "USL", type: "number" },
    { name: "critical", label: "Critical", type: "select", required: true, options: ["yes", "no"] },
  ],
  inspections: [
    { name: "code", label: "Inspection No.", type: "text", placeholder: "auto-generated" },
    { name: "stage", label: "Stage", type: "select", required: true, options: ["incoming", "in-process", "final"] },
    { name: "refType", label: "Reference Type", type: "select", required: true, options: ["GRN", "WO", "FG", "PROJ"] },
    { name: "refCode", label: "Reference No.", type: "text", required: true },
    { name: "checklistCode", label: "Inspection Plan", type: "combobox", optionsKey: "checklists", required: true },
    { name: "itemCode", label: "Item Code", type: "combobox", optionsKey: "items", required: true },
    { name: "itemDescription", label: "Item Description", type: "text", required: true, colSpan: 2 },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "vendorName", label: "Vendor", type: "combobox", optionsKey: "vendors" },
    { name: "projectCode", label: "Project Code", type: "combobox", optionsKey: "projects" },
    { name: "inspector", label: "Inspector", type: "combobox", optionsKey: "inspectors", required: true },
    { name: "scheduledFor", label: "Scheduled For", type: "date", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["planned", "in-progress", "passed", "failed", "rework"] },
    { name: "criticalDefects", label: "Critical Defects", type: "number" },
    { name: "majorDefects", label: "Major Defects", type: "number" },
    { name: "minorDefects", label: "Minor Defects", type: "number" },
    { name: "remarks", label: "Remarks", type: "textarea", colSpan: 2 },
  ],
  ncrs: [
    { name: "code", label: "NCR No.", type: "text", placeholder: "auto-generated" },
    { name: "source", label: "Source", type: "select", required: true, options: ["incoming", "in-process", "final", "customer", "audit"] },
    { name: "raisedBy", label: "Raised By", type: "combobox", optionsKey: "inspectors", required: true },
    { name: "raisedAt", label: "Raised On", type: "date", required: true },
    { name: "itemCode", label: "Item Code", type: "combobox", optionsKey: "items", required: true },
    { name: "itemDescription", label: "Item Description", type: "text", required: true, colSpan: 2 },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "vendorName", label: "Vendor", type: "combobox", optionsKey: "vendors" },
    { name: "projectCode", label: "Project Code", type: "combobox", optionsKey: "projects" },
    { name: "defect", label: "Defect Description", type: "textarea", required: true, colSpan: 2 },
    { name: "severity", label: "Severity", type: "select", required: true, options: ["low", "medium", "high", "critical"] },
    { name: "disposition", label: "Disposition", type: "select", options: ["rework", "scrap", "use-as-is", "return-to-vendor"] },
    { name: "status", label: "Status", type: "select", required: true, options: ["open", "investigation", "containment", "resolved", "closed"] },
    { name: "containment", label: "Containment Action", type: "textarea", colSpan: 2 },
    { name: "costImpact", label: "Cost Impact (INR)", type: "number", required: true },
  ],
  capas: [
    { name: "code", label: "CAPA No.", type: "text", placeholder: "auto-generated" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "ncrCode", label: "Linked NCR", type: "combobox", optionsKey: "ncrs" },
    { name: "owner", label: "Owner", type: "combobox", optionsKey: "inspectors", required: true },
    { name: "openedAt", label: "Opened On", type: "date", required: true },
    { name: "targetClose", label: "Target Close", type: "date", required: true },
    { name: "stage", label: "8D Stage", type: "select", required: true, options: ["D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8"] },
    { name: "status", label: "Status", type: "select", required: true, options: ["open", "in-progress", "verification", "closed", "overdue"] },
    { name: "rootCause", label: "Root Cause (D4)", type: "textarea", colSpan: 2 },
    { name: "correctiveAction", label: "Corrective Action (D5)", type: "textarea", colSpan: 2 },
    { name: "preventiveAction", label: "Preventive Action (D7)", type: "textarea", colSpan: 2 },
    { name: "effectivenessPct", label: "Effectiveness %", type: "number" },
  ],
  gauges: [
    { name: "code", label: "Gauge Code", type: "text", placeholder: "auto-generated" },
    { name: "name", label: "Gauge Name", type: "text", required: true, colSpan: 2 },
    { name: "type", label: "Type", type: "text", required: true },
    { name: "location", label: "Location", type: "text", required: true },
    { name: "owner", label: "Owner", type: "combobox", optionsKey: "inspectors", required: true },
    { name: "range", label: "Range", type: "text", required: true },
    { name: "leastCount", label: "Least Count", type: "text", required: true },
    { name: "lastCalibrated", label: "Last Calibrated", type: "date", required: true },
    { name: "frequencyDays", label: "Frequency (days)", type: "number", required: true },
    { name: "nextDue", label: "Next Due", type: "date" },
    { name: "provider", label: "Calibration Provider", type: "text", required: true },
    { name: "certificateNo", label: "Certificate No.", type: "text" },
    { name: "status", label: "Status", type: "select", options: ["in-cal", "due-soon", "overdue", "out-of-service"] },
  ],
  calibration: [
    { name: "lastCalibrated", label: "Calibrated On", type: "date", required: true },
    { name: "provider", label: "Provider", type: "text", required: true },
    { name: "certificateNo", label: "Certificate No.", type: "text", required: true },
    { name: "frequencyDays", label: "Next Frequency (days)", type: "number", required: true },
  ],
  suppliers: [
    { name: "vendorCode", label: "Vendor Code", type: "text", required: true },
    { name: "vendorName", label: "Vendor", type: "combobox", optionsKey: "vendors", required: true, colSpan: 2 },
    { name: "category", label: "Category", type: "text", required: true },
    { name: "lotsReceived", label: "Lots Received", type: "number", required: true },
    { name: "lotsAccepted", label: "Lots Accepted", type: "number", required: true },
    { name: "ppm", label: "Defect PPM", type: "number", required: true },
    { name: "otdPct", label: "On-Time Delivery %", type: "number", required: true },
    { name: "ncrCount", label: "Open NCRs", type: "number", required: true },
    { name: "responseHours", label: "Response Time (hrs)", type: "number", required: true },
  ],
};
