import type { FieldSpec } from "@/components/record-dialog";
import { DOWNTIME_REASONS } from "./types";

export const MFG_SCHEMAS: Record<string, FieldSpec[]> = {
  orders: [
    { name: "itemCode", label: "Item Code", type: "combobox", optionsKey: "plmItems", required: true },
    { name: "itemName", label: "Item Name", type: "text", required: true, colSpan: 2 },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "routingCode", label: "Routing", type: "combobox", optionsKey: "routings" },
    { name: "projectCode", label: "Project", type: "combobox", optionsKey: "projects" },
    { name: "bomRootId", label: "Linked BOM", type: "combobox", optionsKey: "bomRoots" },
    { name: "priority", label: "Priority", type: "select", options: ["Low", "Normal", "High", "Critical"] },
    { name: "status", label: "Status", type: "select", options: ["planned", "released", "in-progress", "completed", "closed", "cancelled"] },
    { name: "plannedStart", label: "Planned Start", type: "date" },
    { name: "dueDate", label: "Due Date", type: "date", required: true },
  ],
  workCenters: [
    { name: "code", label: "Work Center Code", type: "text", required: true, placeholder: "WC-WELD" },
    { name: "name", label: "Name", type: "text", required: true, colSpan: 2 },
    { name: "type", label: "Type", type: "select", required: true, options: ["Weld", "Machining", "Assembly", "Paint", "Sub-contract"] },
    { name: "location", label: "Location", type: "text" },
    { name: "shifts", label: "Shifts per day", type: "number", required: true },
    { name: "capacityHrsPerShift", label: "Hours per shift", type: "number", required: true },
    { name: "hourlyRate", label: "Conversion rate (₹/hr)", type: "number", required: true },
    { name: "oeeTarget", label: "OEE target (%)", type: "number", required: true },
  ],
  routings: [
    { name: "code", label: "Routing Code", type: "text", required: true, placeholder: "RT-BIW-100" },
    { name: "itemCode", label: "Item Code", type: "combobox", optionsKey: "plmItems", required: true },
    { name: "itemName", label: "Item Name", type: "text", required: true, colSpan: 2 },
    { name: "rev", label: "Revision", type: "select", options: ["A", "B", "C", "D", "E"] },
  ],
  routingOps: [
    { name: "routingCode", label: "Routing", type: "combobox", optionsKey: "routings", required: true },
    { name: "seq", label: "Sequence", type: "number", required: true },
    { name: "name", label: "Operation", type: "text", required: true, colSpan: 2 },
    { name: "workCenterCode", label: "Work Center", type: "combobox", optionsKey: "workCenters", required: true },
    { name: "setupMins", label: "Setup (mins)", type: "number", required: true },
    { name: "runMinsPerUnit", label: "Run time / unit (mins)", type: "number", required: true },
    { name: "inspection", label: "In-process inspection", type: "select", options: ["true", "false"] },
    { name: "subcontract", label: "Sub-contracted", type: "select", options: ["true", "false"] },
  ],
  jobWork: [
    { name: "vendor", label: "Vendor", type: "text", required: true, colSpan: 2 },
    { name: "orderCode", label: "Manufacturing Order", type: "combobox", optionsKey: "orders" },
    { name: "itemCode", label: "Item Code", type: "combobox", optionsKey: "plmItems", required: true },
    { name: "itemName", label: "Item Name", type: "text", required: true, colSpan: 2 },
    { name: "qty", label: "Quantity issued", type: "number", required: true },
    { name: "jobRate", label: "Job rate (₹/unit)", type: "number", required: true },
    { name: "issuedValue", label: "Material value issued (₹)", type: "number" },
    { name: "projectCode", label: "Project", type: "combobox", optionsKey: "projects" },
    { name: "issuedAt", label: "Issued on", type: "date" },
    { name: "dueAt", label: "Expected back", type: "date", required: true },
    { name: "status", label: "Status", type: "select", options: ["issued", "partial", "received", "closed"] },
  ],
  downtime: [
    { name: "workCenterCode", label: "Work Center", type: "combobox", optionsKey: "workCenters", required: true },
    { name: "orderCode", label: "Order", type: "combobox", optionsKey: "orders" },
    { name: "reason", label: "Reason", type: "select", required: true, options: [...DOWNTIME_REASONS] },
    { name: "mins", label: "Minutes lost", type: "number", required: true },
    { name: "note", label: "Note", type: "textarea", colSpan: 2 },
  ],
};
