/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedManufacturingRouteImport } from './routes/_authenticated/manufacturing'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedGstRouteImport } from './routes/_authenticated/gst'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedEngineeringRouteImport } from './routes/_authenticated/engineering'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedQualityIndexRouteImport } from './routes/_authenticated/quality.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProcurementIndexRouteImport } from './routes/_authenticated/procurement.index'
import { Route as AuthenticatedMastersIndexRouteImport } from './routes/_authenticated/masters.index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated/hr.index'
import { Route as AuthenticatedGstIndexRouteImport } from './routes/_authenticated/gst.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedEngineeringIndexRouteImport } from './routes/_authenticated/engineering.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedAdministrationIndexRouteImport } from './routes/_authenticated/administration.index'
import { Route as AuthenticatedReportsSectionRouteImport } from './routes/_authenticated/reports.$section'
import { Route as AuthenticatedQualitySectionRouteImport } from './routes/_authenticated/quality.$section'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedProcurementSectionRouteImport } from './routes/_authenticated/procurement.$section'
import { Route as AuthenticatedInventorySectionRouteImport } from './routes/_authenticated/inventory.$section'
import { Route as AuthenticatedHrSectionRouteImport } from './routes/_authenticated/hr.$section'
import { Route as AuthenticatedGstSectionRouteImport } from './routes/_authenticated/gst.$section'
import { Route as AuthenticatedFinanceSectionRouteImport } from './routes/_authenticated/finance.$section'
import { Route as AuthenticatedEngineeringSectionRouteImport } from './routes/_authenticated/engineering.$section'
import { Route as AuthenticatedCrmEntityRouteImport } from './routes/_authenticated/crm.$entity'
import { Route as AuthenticatedAdministrationSectionRouteImport } from './routes/_authenticated/administration.$section'
import { Route as AuthenticatedMastersMasterIndexRouteImport } from './routes/_authenticated/masters.$master.index'
import { Route as AuthenticatedMastersMasterNewRouteImport } from './routes/_authenticated/masters.$master.new'
import { Route as AuthenticatedCrmEntityIdRouteImport } from './routes/_authenticated/crm.$entity.$id'
import { Route as AuthenticatedMastersMasterIdIndexRouteImport } from './routes/_authenticated/masters.$master.$id.index'
import { Route as AuthenticatedMastersMasterIdEditRouteImport } from './routes/_authenticated/masters.$master.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingRoute =
  AuthenticatedManufacturingRouteImport.update({
    id: '/manufacturing',
    path: '/manufacturing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGstRoute = AuthenticatedGstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineeringRoute =
  AuthenticatedEngineeringRouteImport.update({
    id: '/engineering',
    path: '/engineering',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedQualityIndexRoute =
  AuthenticatedQualityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedQualityRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProcurementIndexRoute =
  AuthenticatedProcurementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProcurementRoute,
  } as any)
const AuthenticatedMastersIndexRoute =
  AuthenticatedMastersIndexRouteImport.update({
    id: '/masters/',
    path: '/masters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedGstIndexRoute = AuthenticatedGstIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGstRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedEngineeringIndexRoute =
  AuthenticatedEngineeringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEngineeringRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedAdministrationIndexRoute =
  AuthenticatedAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedReportsSectionRoute =
  AuthenticatedReportsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedQualitySectionRoute =
  AuthenticatedQualitySectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedQualityRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedProcurementSectionRoute =
  AuthenticatedProcurementSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedProcurementRoute,
  } as any)
const AuthenticatedInventorySectionRoute =
  AuthenticatedInventorySectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedHrSectionRoute = AuthenticatedHrSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)
const AuthenticatedGstSectionRoute = AuthenticatedGstSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AuthenticatedGstRoute,
} as any)
const AuthenticatedFinanceSectionRoute =
  AuthenticatedFinanceSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedEngineeringSectionRoute =
  AuthenticatedEngineeringSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedEngineeringRoute,
  } as any)
const AuthenticatedCrmEntityRoute = AuthenticatedCrmEntityRouteImport.update({
  id: '/$entity',
  path: '/$entity',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedAdministrationSectionRoute =
  AuthenticatedAdministrationSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedAdministrationRoute,
  } as any)
const AuthenticatedMastersMasterIndexRoute =
  AuthenticatedMastersMasterIndexRouteImport.update({
    id: '/masters/$master/',
    path: '/masters/$master/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMasterNewRoute =
  AuthenticatedMastersMasterNewRouteImport.update({
    id: '/masters/$master/new',
    path: '/masters/$master/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmEntityIdRoute =
  AuthenticatedCrmEntityIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCrmEntityRoute,
  } as any)
const AuthenticatedMastersMasterIdIndexRoute =
  AuthenticatedMastersMasterIdIndexRouteImport.update({
    id: '/masters/$master/$id/',
    path: '/masters/$master/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMasterIdEditRoute =
  AuthenticatedMastersMasterIdEditRouteImport.update({
    id: '/masters/$master/$id/edit',
    path: '/masters/$master/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/demo': typeof AuthenticatedDemoRoute
  '/engineering': typeof AuthenticatedEngineeringRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/gst': typeof AuthenticatedGstRouteWithChildren
  '/hr': typeof AuthenticatedHrRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/procurement': typeof AuthenticatedProcurementRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/quality': typeof AuthenticatedQualityRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/administration/$section': typeof AuthenticatedAdministrationSectionRoute
  '/crm/$entity': typeof AuthenticatedCrmEntityRouteWithChildren
  '/engineering/$section': typeof AuthenticatedEngineeringSectionRoute
  '/finance/$section': typeof AuthenticatedFinanceSectionRoute
  '/gst/$section': typeof AuthenticatedGstSectionRoute
  '/hr/$section': typeof AuthenticatedHrSectionRoute
  '/inventory/$section': typeof AuthenticatedInventorySectionRoute
  '/procurement/$section': typeof AuthenticatedProcurementSectionRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/quality/$section': typeof AuthenticatedQualitySectionRoute
  '/reports/$section': typeof AuthenticatedReportsSectionRoute
  '/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/engineering/': typeof AuthenticatedEngineeringIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/gst/': typeof AuthenticatedGstIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/masters/': typeof AuthenticatedMastersIndexRoute
  '/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/quality/': typeof AuthenticatedQualityIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/crm/$entity/$id': typeof AuthenticatedCrmEntityIdRoute
  '/masters/$master/new': typeof AuthenticatedMastersMasterNewRoute
  '/masters/$master/': typeof AuthenticatedMastersMasterIndexRoute
  '/masters/$master/$id/edit': typeof AuthenticatedMastersMasterIdEditRoute
  '/masters/$master/$id/': typeof AuthenticatedMastersMasterIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/administration/$section': typeof AuthenticatedAdministrationSectionRoute
  '/crm/$entity': typeof AuthenticatedCrmEntityRouteWithChildren
  '/engineering/$section': typeof AuthenticatedEngineeringSectionRoute
  '/finance/$section': typeof AuthenticatedFinanceSectionRoute
  '/gst/$section': typeof AuthenticatedGstSectionRoute
  '/hr/$section': typeof AuthenticatedHrSectionRoute
  '/inventory/$section': typeof AuthenticatedInventorySectionRoute
  '/procurement/$section': typeof AuthenticatedProcurementSectionRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/quality/$section': typeof AuthenticatedQualitySectionRoute
  '/reports/$section': typeof AuthenticatedReportsSectionRoute
  '/administration': typeof AuthenticatedAdministrationIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/engineering': typeof AuthenticatedEngineeringIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/gst': typeof AuthenticatedGstIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/masters': typeof AuthenticatedMastersIndexRoute
  '/procurement': typeof AuthenticatedProcurementIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/quality': typeof AuthenticatedQualityIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/crm/$entity/$id': typeof AuthenticatedCrmEntityIdRoute
  '/masters/$master/new': typeof AuthenticatedMastersMasterNewRoute
  '/masters/$master': typeof AuthenticatedMastersMasterIndexRoute
  '/masters/$master/$id/edit': typeof AuthenticatedMastersMasterIdEditRoute
  '/masters/$master/$id': typeof AuthenticatedMastersMasterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRouteWithChildren
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/engineering': typeof AuthenticatedEngineeringRouteWithChildren
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/gst': typeof AuthenticatedGstRouteWithChildren
  '/_authenticated/hr': typeof AuthenticatedHrRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/_authenticated/manufacturing': typeof AuthenticatedManufacturingRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/quality': typeof AuthenticatedQualityRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/administration/$section': typeof AuthenticatedAdministrationSectionRoute
  '/_authenticated/crm/$entity': typeof AuthenticatedCrmEntityRouteWithChildren
  '/_authenticated/engineering/$section': typeof AuthenticatedEngineeringSectionRoute
  '/_authenticated/finance/$section': typeof AuthenticatedFinanceSectionRoute
  '/_authenticated/gst/$section': typeof AuthenticatedGstSectionRoute
  '/_authenticated/hr/$section': typeof AuthenticatedHrSectionRoute
  '/_authenticated/inventory/$section': typeof AuthenticatedInventorySectionRoute
  '/_authenticated/procurement/$section': typeof AuthenticatedProcurementSectionRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/quality/$section': typeof AuthenticatedQualitySectionRoute
  '/_authenticated/reports/$section': typeof AuthenticatedReportsSectionRoute
  '/_authenticated/administration/': typeof AuthenticatedAdministrationIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/engineering/': typeof AuthenticatedEngineeringIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/gst/': typeof AuthenticatedGstIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/masters/': typeof AuthenticatedMastersIndexRoute
  '/_authenticated/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/quality/': typeof AuthenticatedQualityIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/crm/$entity/$id': typeof AuthenticatedCrmEntityIdRoute
  '/_authenticated/masters/$master/new': typeof AuthenticatedMastersMasterNewRoute
  '/_authenticated/masters/$master/': typeof AuthenticatedMastersMasterIndexRoute
  '/_authenticated/masters/$master/$id/edit': typeof AuthenticatedMastersMasterIdEditRoute
  '/_authenticated/masters/$master/$id/': typeof AuthenticatedMastersMasterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administration'
    | '/ai-assistant'
    | '/crm'
    | '/demo'
    | '/engineering'
    | '/finance'
    | '/gst'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/procurement'
    | '/profile'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/api/chat'
    | '/auth/forgot-password'
    | '/administration/$section'
    | '/crm/$entity'
    | '/engineering/$section'
    | '/finance/$section'
    | '/gst/$section'
    | '/hr/$section'
    | '/inventory/$section'
    | '/procurement/$section'
    | '/projects/$id'
    | '/quality/$section'
    | '/reports/$section'
    | '/administration/'
    | '/crm/'
    | '/engineering/'
    | '/finance/'
    | '/gst/'
    | '/hr/'
    | '/inventory/'
    | '/masters/'
    | '/procurement/'
    | '/projects/'
    | '/quality/'
    | '/reports/'
    | '/crm/$entity/$id'
    | '/masters/$master/new'
    | '/masters/$master/'
    | '/masters/$master/$id/edit'
    | '/masters/$master/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/ai-assistant'
    | '/demo'
    | '/manufacturing'
    | '/profile'
    | '/settings'
    | '/api/chat'
    | '/auth/forgot-password'
    | '/'
    | '/administration/$section'
    | '/crm/$entity'
    | '/engineering/$section'
    | '/finance/$section'
    | '/gst/$section'
    | '/hr/$section'
    | '/inventory/$section'
    | '/procurement/$section'
    | '/projects/$id'
    | '/quality/$section'
    | '/reports/$section'
    | '/administration'
    | '/crm'
    | '/engineering'
    | '/finance'
    | '/gst'
    | '/hr'
    | '/inventory'
    | '/masters'
    | '/procurement'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/crm/$entity/$id'
    | '/masters/$master/new'
    | '/masters/$master'
    | '/masters/$master/$id/edit'
    | '/masters/$master/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/administration'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/crm'
    | '/_authenticated/demo'
    | '/_authenticated/engineering'
    | '/_authenticated/finance'
    | '/_authenticated/gst'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/manufacturing'
    | '/_authenticated/procurement'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/quality'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/auth/forgot-password'
    | '/_authenticated/'
    | '/_authenticated/administration/$section'
    | '/_authenticated/crm/$entity'
    | '/_authenticated/engineering/$section'
    | '/_authenticated/finance/$section'
    | '/_authenticated/gst/$section'
    | '/_authenticated/hr/$section'
    | '/_authenticated/inventory/$section'
    | '/_authenticated/procurement/$section'
    | '/_authenticated/projects/$id'
    | '/_authenticated/quality/$section'
    | '/_authenticated/reports/$section'
    | '/_authenticated/administration/'
    | '/_authenticated/crm/'
    | '/_authenticated/engineering/'
    | '/_authenticated/finance/'
    | '/_authenticated/gst/'
    | '/_authenticated/hr/'
    | '/_authenticated/inventory/'
    | '/_authenticated/masters/'
    | '/_authenticated/procurement/'
    | '/_authenticated/projects/'
    | '/_authenticated/quality/'
    | '/_authenticated/reports/'
    | '/_authenticated/crm/$entity/$id'
    | '/_authenticated/masters/$master/new'
    | '/_authenticated/masters/$master/'
    | '/_authenticated/masters/$master/$id/edit'
    | '/_authenticated/masters/$master/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing': {
      id: '/_authenticated/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof AuthenticatedManufacturingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gst': {
      id: '/_authenticated/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof AuthenticatedGstRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineering': {
      id: '/_authenticated/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof AuthenticatedEngineeringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/quality/': {
      id: '/_authenticated/quality/'
      path: '/'
      fullPath: '/quality/'
      preLoaderRoute: typeof AuthenticatedQualityIndexRouteImport
      parentRoute: typeof AuthenticatedQualityRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/procurement/': {
      id: '/_authenticated/procurement/'
      path: '/'
      fullPath: '/procurement/'
      preLoaderRoute: typeof AuthenticatedProcurementIndexRouteImport
      parentRoute: typeof AuthenticatedProcurementRoute
    }
    '/_authenticated/masters/': {
      id: '/_authenticated/masters/'
      path: '/masters'
      fullPath: '/masters/'
      preLoaderRoute: typeof AuthenticatedMastersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/gst/': {
      id: '/_authenticated/gst/'
      path: '/'
      fullPath: '/gst/'
      preLoaderRoute: typeof AuthenticatedGstIndexRouteImport
      parentRoute: typeof AuthenticatedGstRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/engineering/': {
      id: '/_authenticated/engineering/'
      path: '/'
      fullPath: '/engineering/'
      preLoaderRoute: typeof AuthenticatedEngineeringIndexRouteImport
      parentRoute: typeof AuthenticatedEngineeringRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/administration/': {
      id: '/_authenticated/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof AuthenticatedAdministrationIndexRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/reports/$section': {
      id: '/_authenticated/reports/$section'
      path: '/$section'
      fullPath: '/reports/$section'
      preLoaderRoute: typeof AuthenticatedReportsSectionRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/quality/$section': {
      id: '/_authenticated/quality/$section'
      path: '/$section'
      fullPath: '/quality/$section'
      preLoaderRoute: typeof AuthenticatedQualitySectionRouteImport
      parentRoute: typeof AuthenticatedQualityRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/procurement/$section': {
      id: '/_authenticated/procurement/$section'
      path: '/$section'
      fullPath: '/procurement/$section'
      preLoaderRoute: typeof AuthenticatedProcurementSectionRouteImport
      parentRoute: typeof AuthenticatedProcurementRoute
    }
    '/_authenticated/inventory/$section': {
      id: '/_authenticated/inventory/$section'
      path: '/$section'
      fullPath: '/inventory/$section'
      preLoaderRoute: typeof AuthenticatedInventorySectionRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/hr/$section': {
      id: '/_authenticated/hr/$section'
      path: '/$section'
      fullPath: '/hr/$section'
      preLoaderRoute: typeof AuthenticatedHrSectionRouteImport
      parentRoute: typeof AuthenticatedHrRoute
    }
    '/_authenticated/gst/$section': {
      id: '/_authenticated/gst/$section'
      path: '/$section'
      fullPath: '/gst/$section'
      preLoaderRoute: typeof AuthenticatedGstSectionRouteImport
      parentRoute: typeof AuthenticatedGstRoute
    }
    '/_authenticated/finance/$section': {
      id: '/_authenticated/finance/$section'
      path: '/$section'
      fullPath: '/finance/$section'
      preLoaderRoute: typeof AuthenticatedFinanceSectionRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/engineering/$section': {
      id: '/_authenticated/engineering/$section'
      path: '/$section'
      fullPath: '/engineering/$section'
      preLoaderRoute: typeof AuthenticatedEngineeringSectionRouteImport
      parentRoute: typeof AuthenticatedEngineeringRoute
    }
    '/_authenticated/crm/$entity': {
      id: '/_authenticated/crm/$entity'
      path: '/$entity'
      fullPath: '/crm/$entity'
      preLoaderRoute: typeof AuthenticatedCrmEntityRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/administration/$section': {
      id: '/_authenticated/administration/$section'
      path: '/$section'
      fullPath: '/administration/$section'
      preLoaderRoute: typeof AuthenticatedAdministrationSectionRouteImport
      parentRoute: typeof AuthenticatedAdministrationRoute
    }
    '/_authenticated/masters/$master/': {
      id: '/_authenticated/masters/$master/'
      path: '/masters/$master'
      fullPath: '/masters/$master/'
      preLoaderRoute: typeof AuthenticatedMastersMasterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/$master/new': {
      id: '/_authenticated/masters/$master/new'
      path: '/masters/$master/new'
      fullPath: '/masters/$master/new'
      preLoaderRoute: typeof AuthenticatedMastersMasterNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/$entity/$id': {
      id: '/_authenticated/crm/$entity/$id'
      path: '/$id'
      fullPath: '/crm/$entity/$id'
      preLoaderRoute: typeof AuthenticatedCrmEntityIdRouteImport
      parentRoute: typeof AuthenticatedCrmEntityRoute
    }
    '/_authenticated/masters/$master/$id/': {
      id: '/_authenticated/masters/$master/$id/'
      path: '/masters/$master/$id'
      fullPath: '/masters/$master/$id/'
      preLoaderRoute: typeof AuthenticatedMastersMasterIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/$master/$id/edit': {
      id: '/_authenticated/masters/$master/$id/edit'
      path: '/masters/$master/$id/edit'
      fullPath: '/masters/$master/$id/edit'
      preLoaderRoute: typeof AuthenticatedMastersMasterIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdministrationRouteChildren {
  AuthenticatedAdministrationSectionRoute: typeof AuthenticatedAdministrationSectionRoute
  AuthenticatedAdministrationIndexRoute: typeof AuthenticatedAdministrationIndexRoute
}

const AuthenticatedAdministrationRouteChildren: AuthenticatedAdministrationRouteChildren =
  {
    AuthenticatedAdministrationSectionRoute:
      AuthenticatedAdministrationSectionRoute,
    AuthenticatedAdministrationIndexRoute:
      AuthenticatedAdministrationIndexRoute,
  }

const AuthenticatedAdministrationRouteWithChildren =
  AuthenticatedAdministrationRoute._addFileChildren(
    AuthenticatedAdministrationRouteChildren,
  )

interface AuthenticatedCrmEntityRouteChildren {
  AuthenticatedCrmEntityIdRoute: typeof AuthenticatedCrmEntityIdRoute
}

const AuthenticatedCrmEntityRouteChildren: AuthenticatedCrmEntityRouteChildren =
  {
    AuthenticatedCrmEntityIdRoute: AuthenticatedCrmEntityIdRoute,
  }

const AuthenticatedCrmEntityRouteWithChildren =
  AuthenticatedCrmEntityRoute._addFileChildren(
    AuthenticatedCrmEntityRouteChildren,
  )

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmEntityRoute: typeof AuthenticatedCrmEntityRouteWithChildren
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmEntityRoute: AuthenticatedCrmEntityRouteWithChildren,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedEngineeringRouteChildren {
  AuthenticatedEngineeringSectionRoute: typeof AuthenticatedEngineeringSectionRoute
  AuthenticatedEngineeringIndexRoute: typeof AuthenticatedEngineeringIndexRoute
}

const AuthenticatedEngineeringRouteChildren: AuthenticatedEngineeringRouteChildren =
  {
    AuthenticatedEngineeringSectionRoute: AuthenticatedEngineeringSectionRoute,
    AuthenticatedEngineeringIndexRoute: AuthenticatedEngineeringIndexRoute,
  }

const AuthenticatedEngineeringRouteWithChildren =
  AuthenticatedEngineeringRoute._addFileChildren(
    AuthenticatedEngineeringRouteChildren,
  )

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceSectionRoute: typeof AuthenticatedFinanceSectionRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceSectionRoute: AuthenticatedFinanceSectionRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedGstRouteChildren {
  AuthenticatedGstSectionRoute: typeof AuthenticatedGstSectionRoute
  AuthenticatedGstIndexRoute: typeof AuthenticatedGstIndexRoute
}

const AuthenticatedGstRouteChildren: AuthenticatedGstRouteChildren = {
  AuthenticatedGstSectionRoute: AuthenticatedGstSectionRoute,
  AuthenticatedGstIndexRoute: AuthenticatedGstIndexRoute,
}

const AuthenticatedGstRouteWithChildren =
  AuthenticatedGstRoute._addFileChildren(AuthenticatedGstRouteChildren)

interface AuthenticatedHrRouteChildren {
  AuthenticatedHrSectionRoute: typeof AuthenticatedHrSectionRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
}

const AuthenticatedHrRouteChildren: AuthenticatedHrRouteChildren = {
  AuthenticatedHrSectionRoute: AuthenticatedHrSectionRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
}

const AuthenticatedHrRouteWithChildren = AuthenticatedHrRoute._addFileChildren(
  AuthenticatedHrRouteChildren,
)

interface AuthenticatedInventoryRouteChildren {
  AuthenticatedInventorySectionRoute: typeof AuthenticatedInventorySectionRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
}

const AuthenticatedInventoryRouteChildren: AuthenticatedInventoryRouteChildren =
  {
    AuthenticatedInventorySectionRoute: AuthenticatedInventorySectionRoute,
    AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  }

const AuthenticatedInventoryRouteWithChildren =
  AuthenticatedInventoryRoute._addFileChildren(
    AuthenticatedInventoryRouteChildren,
  )

interface AuthenticatedProcurementRouteChildren {
  AuthenticatedProcurementSectionRoute: typeof AuthenticatedProcurementSectionRoute
  AuthenticatedProcurementIndexRoute: typeof AuthenticatedProcurementIndexRoute
}

const AuthenticatedProcurementRouteChildren: AuthenticatedProcurementRouteChildren =
  {
    AuthenticatedProcurementSectionRoute: AuthenticatedProcurementSectionRoute,
    AuthenticatedProcurementIndexRoute: AuthenticatedProcurementIndexRoute,
  }

const AuthenticatedProcurementRouteWithChildren =
  AuthenticatedProcurementRoute._addFileChildren(
    AuthenticatedProcurementRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedQualityRouteChildren {
  AuthenticatedQualitySectionRoute: typeof AuthenticatedQualitySectionRoute
  AuthenticatedQualityIndexRoute: typeof AuthenticatedQualityIndexRoute
}

const AuthenticatedQualityRouteChildren: AuthenticatedQualityRouteChildren = {
  AuthenticatedQualitySectionRoute: AuthenticatedQualitySectionRoute,
  AuthenticatedQualityIndexRoute: AuthenticatedQualityIndexRoute,
}

const AuthenticatedQualityRouteWithChildren =
  AuthenticatedQualityRoute._addFileChildren(AuthenticatedQualityRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsSectionRoute: typeof AuthenticatedReportsSectionRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsSectionRoute: AuthenticatedReportsSectionRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRouteWithChildren
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedEngineeringRoute: typeof AuthenticatedEngineeringRouteWithChildren
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedGstRoute: typeof AuthenticatedGstRouteWithChildren
  AuthenticatedHrRoute: typeof AuthenticatedHrRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRouteWithChildren
  AuthenticatedManufacturingRoute: typeof AuthenticatedManufacturingRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMastersIndexRoute: typeof AuthenticatedMastersIndexRoute
  AuthenticatedMastersMasterNewRoute: typeof AuthenticatedMastersMasterNewRoute
  AuthenticatedMastersMasterIndexRoute: typeof AuthenticatedMastersMasterIndexRoute
  AuthenticatedMastersMasterIdEditRoute: typeof AuthenticatedMastersMasterIdEditRoute
  AuthenticatedMastersMasterIdIndexRoute: typeof AuthenticatedMastersMasterIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrationRoute:
    AuthenticatedAdministrationRouteWithChildren,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedEngineeringRoute: AuthenticatedEngineeringRouteWithChildren,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedGstRoute: AuthenticatedGstRouteWithChildren,
  AuthenticatedHrRoute: AuthenticatedHrRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRouteWithChildren,
  AuthenticatedManufacturingRoute: AuthenticatedManufacturingRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedQualityRoute: AuthenticatedQualityRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMastersIndexRoute: AuthenticatedMastersIndexRoute,
  AuthenticatedMastersMasterNewRoute: AuthenticatedMastersMasterNewRoute,
  AuthenticatedMastersMasterIndexRoute: AuthenticatedMastersMasterIndexRoute,
  AuthenticatedMastersMasterIdEditRoute: AuthenticatedMastersMasterIdEditRoute,
  AuthenticatedMastersMasterIdIndexRoute:
    AuthenticatedMastersMasterIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
