/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQualityRouteImport } from './routes/_authenticated/quality'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedManufacturingRouteImport } from './routes/_authenticated/manufacturing'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedEngineeringRouteImport } from './routes/_authenticated/engineering'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedAdministrationRouteImport } from './routes/_authenticated/administration'
import { Route as AuthenticatedMastersIndexRouteImport } from './routes/_authenticated/masters.index'
import { Route as AuthenticatedMastersMasterIndexRouteImport } from './routes/_authenticated/masters.$master.index'
import { Route as AuthenticatedMastersMasterNewRouteImport } from './routes/_authenticated/masters.$master.new'
import { Route as AuthenticatedMastersMasterIdIndexRouteImport } from './routes/_authenticated/masters.$master.$id.index'
import { Route as AuthenticatedMastersMasterIdEditRouteImport } from './routes/_authenticated/masters.$master.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualityRoute = AuthenticatedQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingRoute =
  AuthenticatedManufacturingRouteImport.update({
    id: '/manufacturing',
    path: '/manufacturing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineeringRoute =
  AuthenticatedEngineeringRouteImport.update({
    id: '/engineering',
    path: '/engineering',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministrationRoute =
  AuthenticatedAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersIndexRoute =
  AuthenticatedMastersIndexRouteImport.update({
    id: '/masters/',
    path: '/masters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMasterIndexRoute =
  AuthenticatedMastersMasterIndexRouteImport.update({
    id: '/masters/$master/',
    path: '/masters/$master/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMasterNewRoute =
  AuthenticatedMastersMasterNewRouteImport.update({
    id: '/masters/$master/new',
    path: '/masters/$master/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMasterIdIndexRoute =
  AuthenticatedMastersMasterIdIndexRouteImport.update({
    id: '/masters/$master/$id/',
    path: '/masters/$master/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMasterIdEditRoute =
  AuthenticatedMastersMasterIdEditRouteImport.update({
    id: '/masters/$master/$id/edit',
    path: '/masters/$master/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/engineering': typeof AuthenticatedEngineeringRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/masters/': typeof AuthenticatedMastersIndexRoute
  '/masters/$master/new': typeof AuthenticatedMastersMasterNewRoute
  '/masters/$master/': typeof AuthenticatedMastersMasterIndexRoute
  '/masters/$master/$id/edit': typeof AuthenticatedMastersMasterIdEditRoute
  '/masters/$master/$id/': typeof AuthenticatedMastersMasterIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/administration': typeof AuthenticatedAdministrationRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/engineering': typeof AuthenticatedEngineeringRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/quality': typeof AuthenticatedQualityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/masters': typeof AuthenticatedMastersIndexRoute
  '/masters/$master/new': typeof AuthenticatedMastersMasterNewRoute
  '/masters/$master': typeof AuthenticatedMastersMasterIndexRoute
  '/masters/$master/$id/edit': typeof AuthenticatedMastersMasterIdEditRoute
  '/masters/$master/$id': typeof AuthenticatedMastersMasterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administration': typeof AuthenticatedAdministrationRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/engineering': typeof AuthenticatedEngineeringRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/manufacturing': typeof AuthenticatedManufacturingRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/quality': typeof AuthenticatedQualityRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/masters/': typeof AuthenticatedMastersIndexRoute
  '/_authenticated/masters/$master/new': typeof AuthenticatedMastersMasterNewRoute
  '/_authenticated/masters/$master/': typeof AuthenticatedMastersMasterIndexRoute
  '/_authenticated/masters/$master/$id/edit': typeof AuthenticatedMastersMasterIdEditRoute
  '/_authenticated/masters/$master/$id/': typeof AuthenticatedMastersMasterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administration'
    | '/ai-assistant'
    | '/engineering'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/procurement'
    | '/profile'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/auth/forgot-password'
    | '/masters/'
    | '/masters/$master/new'
    | '/masters/$master/'
    | '/masters/$master/$id/edit'
    | '/masters/$master/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/administration'
    | '/ai-assistant'
    | '/engineering'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/procurement'
    | '/profile'
    | '/projects'
    | '/quality'
    | '/reports'
    | '/settings'
    | '/auth/forgot-password'
    | '/'
    | '/masters'
    | '/masters/$master/new'
    | '/masters/$master'
    | '/masters/$master/$id/edit'
    | '/masters/$master/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/administration'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/engineering'
    | '/_authenticated/finance'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/manufacturing'
    | '/_authenticated/procurement'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/quality'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/auth/forgot-password'
    | '/_authenticated/'
    | '/_authenticated/masters/'
    | '/_authenticated/masters/$master/new'
    | '/_authenticated/masters/$master/'
    | '/_authenticated/masters/$master/$id/edit'
    | '/_authenticated/masters/$master/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quality': {
      id: '/_authenticated/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AuthenticatedQualityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing': {
      id: '/_authenticated/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof AuthenticatedManufacturingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineering': {
      id: '/_authenticated/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof AuthenticatedEngineeringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administration': {
      id: '/_authenticated/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AuthenticatedAdministrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/': {
      id: '/_authenticated/masters/'
      path: '/masters'
      fullPath: '/masters/'
      preLoaderRoute: typeof AuthenticatedMastersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/$master/': {
      id: '/_authenticated/masters/$master/'
      path: '/masters/$master'
      fullPath: '/masters/$master/'
      preLoaderRoute: typeof AuthenticatedMastersMasterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/$master/new': {
      id: '/_authenticated/masters/$master/new'
      path: '/masters/$master/new'
      fullPath: '/masters/$master/new'
      preLoaderRoute: typeof AuthenticatedMastersMasterNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/$master/$id/': {
      id: '/_authenticated/masters/$master/$id/'
      path: '/masters/$master/$id'
      fullPath: '/masters/$master/$id/'
      preLoaderRoute: typeof AuthenticatedMastersMasterIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/$master/$id/edit': {
      id: '/_authenticated/masters/$master/$id/edit'
      path: '/masters/$master/$id/edit'
      fullPath: '/masters/$master/$id/edit'
      preLoaderRoute: typeof AuthenticatedMastersMasterIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrationRoute: typeof AuthenticatedAdministrationRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedEngineeringRoute: typeof AuthenticatedEngineeringRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedManufacturingRoute: typeof AuthenticatedManufacturingRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedQualityRoute: typeof AuthenticatedQualityRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMastersIndexRoute: typeof AuthenticatedMastersIndexRoute
  AuthenticatedMastersMasterNewRoute: typeof AuthenticatedMastersMasterNewRoute
  AuthenticatedMastersMasterIndexRoute: typeof AuthenticatedMastersMasterIndexRoute
  AuthenticatedMastersMasterIdEditRoute: typeof AuthenticatedMastersMasterIdEditRoute
  AuthenticatedMastersMasterIdIndexRoute: typeof AuthenticatedMastersMasterIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrationRoute: AuthenticatedAdministrationRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedEngineeringRoute: AuthenticatedEngineeringRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedManufacturingRoute: AuthenticatedManufacturingRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedQualityRoute: AuthenticatedQualityRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMastersIndexRoute: AuthenticatedMastersIndexRoute,
  AuthenticatedMastersMasterNewRoute: AuthenticatedMastersMasterNewRoute,
  AuthenticatedMastersMasterIndexRoute: AuthenticatedMastersMasterIndexRoute,
  AuthenticatedMastersMasterIdEditRoute: AuthenticatedMastersMasterIdEditRoute,
  AuthenticatedMastersMasterIdIndexRoute:
    AuthenticatedMastersMasterIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
