import type { FieldSpec } from "@/components/record-dialog";

export const PLM_SCHEMAS: Record<string, FieldSpec[]> = {
  items: [
    { name: "code", label: "Item Code", type: "text", required: true, placeholder: "ITM-1000" },
    { name: "name", label: "Item Name", type: "text", required: true, colSpan: 2 },
    { name: "type", label: "Type", type: "select", required: true, options: ["Raw Material", "Component", "Assembly", "Sub-assembly", "Finished Good", "Consumable"] },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "rev", label: "Revision", type: "select", required: true, options: ["A", "B", "C", "D", "E"] },
    { name: "stdCost", label: "Standard Cost (INR)", type: "number", required: true },
    { name: "make_buy", label: "Make / Buy", type: "select", required: true, options: ["Make", "Buy"] },
    { name: "lifecycle", label: "Lifecycle", type: "select", required: true, options: ["Prototype", "Production", "Obsolete"] },
  ],
  parts: [
    { name: "code", label: "Part Code", type: "text", required: true, placeholder: "PRT-1000" },
    { name: "name", label: "Part Name", type: "text", required: true, colSpan: 2 },
    { name: "category", label: "Category", type: "select", required: true, options: ["Mechanical", "Electrical", "Pneumatic", "Hydraulic", "Fastener", "Standard"] },
    { name: "supplier", label: "Preferred Supplier", type: "text" },
    { name: "material", label: "Material", type: "text" },
    { name: "weight", label: "Weight (kg)", type: "number" },
    { name: "rev", label: "Revision", type: "select", required: true, options: ["A", "B", "C", "D", "E"] },
  ],
  drawings: [
    { name: "number", label: "Drawing Number", type: "text", required: true, placeholder: "DRG-0001" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "itemCode", label: "Linked Item Code", type: "text" },
    { name: "rev", label: "Revision", type: "select", required: true, options: ["A", "B", "C", "D", "E"] },
    { name: "format", label: "Format", type: "select", required: true, options: ["2D-PDF", "2D-DWG", "3D-STEP", "3D-CATIA"] },
    { name: "size", label: "File Size", type: "text", placeholder: "2.4 MB" },
    { name: "uploadedBy", label: "Uploaded By", type: "text", required: true },
    { name: "releasedAt", label: "Released On", type: "date", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["In Work", "Under Review", "Released", "Obsolete"] },
  ],
  bom: [
    { name: "itemCode", label: "Item Code", type: "text", required: true, placeholder: "ITM-1000" },
    { name: "itemName", label: "Item Name", type: "text", required: true, colSpan: 2 },
    { name: "qty", label: "Quantity", type: "number", required: true },
    { name: "uom", label: "UoM", type: "select", required: true, options: ["EA", "KG", "MTR", "SET", "LOT"] },
    { name: "rev", label: "Revision", type: "select", required: true, options: ["A", "B", "C", "D", "E"] },
    { name: "refDes", label: "Reference Designator", type: "text" },
    { name: "procurement", label: "Procurement", type: "select", options: ["Make", "Buy"] },
  ],
  ecns: [
    { name: "code", label: "ECN Number", type: "text", required: true, placeholder: "ECN-0001" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "itemCode", label: "Item Code", type: "text", required: true },
    { name: "fromRev", label: "From Rev", type: "select", required: true, options: ["A", "B", "C", "D", "E"] },
    { name: "toRev", label: "To Rev", type: "select", required: true, options: ["A", "B", "C", "D", "E"] },
    { name: "effectivity", label: "Effectivity Date", type: "date", required: true },
    { name: "raisedBy", label: "Raised By", type: "text", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "pending", "approved", "released", "rejected"] },
    { name: "reason", label: "Reason for Change", type: "textarea", required: true, colSpan: 2 },
  ],
  ecrs: [
    { name: "code", label: "ECR Number", type: "text", required: true, placeholder: "ECR-0001" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "itemCode", label: "Item Code", type: "text", required: true },
    { name: "priority", label: "Priority", type: "select", required: true, options: ["Low", "Medium", "High", "Critical"] },
    { name: "raisedBy", label: "Raised By", type: "text", required: true },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "under-review", "approved", "rejected", "converted"] },
    { name: "linkedEcn", label: "Linked ECN", type: "text" },
    { name: "description", label: "Description", type: "textarea", required: true, colSpan: 2 },
  ],
  reviews: [
    { name: "code", label: "Review Code", type: "text", required: true, placeholder: "DR-0001" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "itemCode", label: "Item Code", type: "text", required: true },
    { name: "scheduled", label: "Scheduled On", type: "date", required: true },
    { name: "outcome", label: "Outcome", type: "select", required: true, options: ["Pending", "Passed", "Passed with Actions", "Failed"] },
    { name: "actions", label: "Open Actions", type: "number" },
    { name: "reviewersText", label: "Reviewers (comma separated)", type: "text", colSpan: 2 },
  ],
};
