import type { FieldSpec } from "@/components/record-dialog";

export const PROCUREMENT_SCHEMAS: Record<string, FieldSpec[]> = {
  vendors: [
    { name: "code", label: "Vendor Code", type: "text", required: true, placeholder: "SUP-1000" },
    { name: "name", label: "Vendor Name", type: "text", required: true, colSpan: 2 },
    { name: "category", label: "Category", type: "select", required: true, options: ["Raw Material", "Components", "Consumables", "Services", "Capital Goods"] },
    { name: "country", label: "Country Code", type: "text", required: true, placeholder: "IN" },
    { name: "city", label: "City", type: "text", required: true },
    { name: "rating", label: "Rating", type: "select", required: true, options: ["A", "B", "C", "Unrated"] },
    { name: "qualification", label: "Qualification", type: "select", required: true, options: ["qualified", "in-review", "conditional", "blacklisted", "draft"] },
    { name: "contact", label: "Contact Person", type: "text", required: true },
    { name: "email", label: "Email", type: "email", required: true },
    { name: "phone", label: "Phone", type: "text" },
    { name: "onTimePct", label: "On-Time Delivery %", type: "number" },
    { name: "qualityPct", label: "Quality %", type: "number" },
    { name: "leadTimeDays", label: "Lead Time (days)", type: "number" },
    { name: "spendYtd", label: "Spend YTD (INR)", type: "number" },
    { name: "certificationsText", label: "Certifications (comma separated)", type: "text", colSpan: 2 },
  ],
  requisitions: [
    { name: "code", label: "PR Number", type: "text", required: true, placeholder: "PR-2400" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "projectCode", label: "Project Code", type: "combobox", optionsKey: "projects", placeholder: "Search active projects…" },
    { name: "department", label: "Department", type: "text", required: true },
    { name: "requestedBy", label: "Requested By", type: "text", required: true },
    { name: "approver", label: "Approver", type: "text" },
    { name: "needBy", label: "Need By", type: "date", required: true },
    { name: "priority", label: "Priority", type: "select", required: true, options: ["low", "medium", "high", "critical"] },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "pending", "approved", "rejected", "converted"] },
    { name: "totalEst", label: "Estimated Value (INR)", type: "number", required: true },
    { name: "notes", label: "Notes", type: "textarea", colSpan: 2 },
  ],
  rfqs: [
    { name: "code", label: "RFQ Number", type: "text", required: true, placeholder: "RFQ-3300" },
    { name: "title", label: "Title", type: "text", required: true, colSpan: 2 },
    { name: "requisitionCode", label: "Source PR", type: "combobox", optionsKey: "prCodes", placeholder: "Search approved requisitions…" },
    { name: "projectCode", label: "Project Code", type: "combobox", optionsKey: "projects", placeholder: "Search active projects…" },
    { name: "buyer", label: "Buyer", type: "combobox", optionsKey: "buyers", required: true, placeholder: "Search buyers…" },
    { name: "issuedAt", label: "Issued On", type: "date", required: true },
    { name: "dueAt", label: "Due On", type: "date", required: true },
    { name: "vendorCount", label: "Vendors Invited", type: "number" },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "issued", "sent", "acknowledged", "bid-received", "under-evaluation", "awarded", "closed", "cancelled"] },
  ],
  pos: [
    { name: "code", label: "PO Number", type: "text", required: true, placeholder: "PO-5500" },
    { name: "vendorName", label: "Vendor", type: "combobox", optionsKey: "vendors", required: true, colSpan: 2, placeholder: "Search vendors…" },
    { name: "rfqCode", label: "Source RFQ", type: "combobox", optionsKey: "rfqCodes", placeholder: "Search RFQs…" },
    { name: "projectCode", label: "Project Code", type: "combobox", optionsKey: "projects", placeholder: "Search active projects…" },
    { name: "buyer", label: "Buyer", type: "text", required: true },
    { name: "currency", label: "Currency", type: "select", required: true, options: ["INR", "USD", "EUR", "JPY"] },
    { name: "promisedDate", label: "Promised Date", type: "date", required: true },
    { name: "amount", label: "PO Value", type: "number", required: true },
    { name: "received", label: "Received Value", type: "number" },
    { name: "invoiced", label: "Invoiced Value", type: "number" },
    { name: "paymentTerms", label: "Payment Terms", type: "text" },
    { name: "incoterms", label: "Incoterms", type: "text" },
    { name: "status", label: "Status", type: "select", required: true, options: ["draft", "pending", "approved", "sent", "acknowledged", "partial", "received", "closed", "cancelled"] },
  ],
  grns: [
    { name: "code", label: "GRN Number", type: "text", required: true, placeholder: "GRN-7700" },
    { name: "poCode", label: "PO Number", type: "combobox", optionsKey: "poCodes", required: true, placeholder: "Search purchase orders…" },
    { name: "vendorName", label: "Vendor", type: "combobox", optionsKey: "vendors", required: true, colSpan: 2, placeholder: "Search vendors…" },
    { name: "receivedAt", label: "Received On", type: "date", required: true },
    { name: "receivedBy", label: "Received By", type: "text", required: true },
    { name: "amount", label: "Amount (INR)", type: "number", required: true },
    { name: "status", label: "GRN Status", type: "select", required: true, options: ["draft", "posted", "quality-hold", "rejected"] },
    { name: "qcResult", label: "QC Result", type: "select", options: ["pending", "passed", "failed"] },
    { name: "invoiceNo", label: "Invoice Number", type: "text" },
    { name: "invoiceMatch", label: "Invoice Match", type: "select", required: true, options: ["unmatched", "matched", "3-way-matched", "hold", "paid"] },
    { name: "invoiceFile", label: "Invoice Copy (PDF)", type: "file", accept: "application/pdf,image/*", colSpan: 2 },
  ],
  amendments: [
    { name: "reason", label: "Amendment Reason", type: "textarea", required: true, colSpan: 2 },
    { name: "fromValue", label: "From Value", type: "number", required: true },
    { name: "toValue", label: "To Value", type: "number", required: true },
    { name: "by", label: "Amended By", type: "text", required: true },
  ],
  bids: [
    { name: "vendorName", label: "Vendor", type: "combobox", optionsKey: "vendors", required: true, colSpan: 2, placeholder: "Search vendors…" },
    { name: "amount", label: "Quoted Amount", type: "number", required: true },
    { name: "leadTimeDays", label: "Lead Time (days)", type: "number", required: true },
    { name: "paymentTerms", label: "Payment Terms", type: "text" },
    { name: "validity", label: "Valid Until", type: "date" },
    { name: "qualityRating", label: "Quality Rating (%)", type: "number" },
    { name: "score", label: "Evaluation Score", type: "number" },
    { name: "notes", label: "Remarks", type: "textarea", colSpan: 2 },
    { name: "quoteFile", label: "Vendor Quotation Copy", type: "file", accept: "application/pdf,image/*", colSpan: 2 },
  ],
};
